### PR TITLE
Restart_needed_issue fix #3006

### LINKED ISSUE #3006: Code related to RESTART_NEEDED is no longer required
In https://github.com/mozilla/testpilot/blob/master/frontend/src/app/lib/InstallManager.js we still have code related to `RESTART_NEEDED` which hasn't ever worked since we stopped using the non-mozAddonManager codepath. All code related to this can be removed now.

### PR DESCRIPTION
**Pull request by marvinsanchez1**
Fix Issue #3006 on Code related to RESTART_NEEDED is no longer required

### CODE REVIEW

**Comment by chuckharmston** [comment]
@msanchez5 Sorry this wasn't communicated yet, but you'll want to make sure that builds are passing before code review. Depending on the context, that may mean either fixing the bugs in your code or adjusting tests to more accurately reflect new expectations.

You can see info about the failed build here: https://circleci.com/gh/mozilla/testpilot/6465

And our testing here: https://github.com/mozilla/testpilot/blob/master/docs/development/testing.md

**Comment by chuckharmston** [comment]
Closing this since we haven't heard back in a few weeks. @msanchez5 feel free to reopen if you ever return to it.

**Comment by marvinsanchez1** [comment]
@chuckharmston sorry about that I got busy with other things and i was focus on #3167 . But I do have a few issues regarding on the environment set up. Before December Test pilot was running fine on my Mac OS, but recently that I updated everything I keep getting this error after I delete the repo and follow the steps on Testpilot. When I go to the IP address or go to the https://example.com:8000/ it shows a blank page...

screen shot 2018-01-22 at 8 11 22 pm 1
screen shot 2018-01-22 at 8 11 44 pm

https://drive.google.com/file/d/10Bk4dMnfgy1RNnxWQrYx0ZAaF4-bt9Y2/view?usp=sharing
https://drive.google.com/file/d/1IFJDsvXo6M8nswC-OulIWojjZmMJrSes/view?usp=sharing

**Comment by SoftVision-PaulOiegas** [comment]
@msanchez5 Have you tried to update the node and npm to latest versions? Had some issues with them on my end too, but on Windows 10. Performed a clean setup afterwards (including re-clone) and it worked.

**Comment by marvinsanchez1** [comment]
@SoftVision-PaulOiegas I tried to update Node, NPM to latest version and re-clone the repo. 
screen shot 2018-01-23 at 8 45 43 pm
I still get the following message.
screen shot 2018-01-23 at 8 43 23 pm

**Comment by SoftVision-PaulOiegas** [comment]
@msanchez5 That's fine, I can still run and test locally with the same error, so I don't think the blank page is because of that. I have just tested today with a fresh clone, so it must be something from your end.

**Pull request closed without merging**
