### PR TITLE
Fixes #3566 [Featured Experiment] Fixed improper string concatenation in renderOneClickInstallButton and renderEnableExperimentButton functions of MainInstallButton component

### LINKED ISSUE #3566: [Featured Experiment] Fix improper string concatenation in renderOneClickInstallButton function of MainInstallButton component
Edit: We are [concatenating two different localized strings in MainInstallButton](https://github.com/mozilla/testpilot/blob/ff322ca8bd5182a3d043a0977ea5cc9a7975c712/frontend/src/app/components/MainInstallButton/index.js#L104) that are part of the same sentence by placing two elements with localized content next to each other and we shouldn't be doing that.

**[Affected versions]:**
- Firefox 61.0b6 and above

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Prerequisites]:**
- Test Pilot repo was cloned locally and server started.
- A Developer Edition browser profile was setup for Local testing as in the "Quickstart" document.
- Notes experiment was set as featured from "notes.yaml" file found in the repo clone.
- Browser language was set to French [fr] from Options > General > Language.
- Test Pilot add-on was already installed. 

**[Steps to reproduce]:**
1. Open Firefox browser with the profile from prerequisites and navigate to 'https://example.com:8000/" page.
2. Observe the green "Activer Notes" button string.
3. Navigate to Experiment details" page and observe the blue "Activer Notes" button.

**[Expected result]:**
- Both buttons are displaying "activer" word with capital "A". 

**[Actual result]:**
- The "Featured Experiment" section wrongly displays "activer" word with lower case "a".

screen shot 2018-05-21 at 12 07 05

### PR DESCRIPTION
**Pull request by KhushilMistry**
Fixes #3566 [Featured Experiment] Fixed improper string concatenation in renderOneClickInstallButton and renderEnableExperimentButton functions of MainInstallButton component

### CODE REVIEW

**Comment by meandavejustice** [comment]
Since the `oneClickInstallMajorCta` id is being replaced with `enableExperiment`. We should do a couple things:

* remove `oneClickInstallMajorCta` from `app.ftl` 
* update `frontend/src/app/containers/ExperimentPage/ExperimentButtons.js` to use the `enableExperiment` id.

Then this should be good to merge :)

**Comment by KhushilMistry** [comment]
Cool Thanks. Will update this PR ASAP.

**Comment by KhushilMistry** [comment]
@meandavejustice How can I remove `oneClickInstallMajorCta` from `app.ftl` ? There are many localizations. And I saw that we are managing this through pontoon. Can you guide me here a little bit?

**Comment by meandavejustice** [comment]
You can just remove it from the `en-US/app.ftl` and the rest will follow suit in our pontoon process.

**Comment by KhushilMistry** [comment]
New

screenshot 2018-10-23 at 1 27 31 am

screenshot 2018-10-23 at 1 28 46 am

Old
screenshot 2018-10-23 at 1 29 33 am

screenshot 2018-10-23 at 1 30 22 am

**Comment by meandavejustice** [comment]
:tada:

**Pull request merged**
