### PR TITLE
Use saner multiline strings in YAML

### LINKED ISSUE #1493: Use saner multiline strings in YAML
YAML allows multiline strings with line breaks stripped:

``` yaml
measurements: >
  In addition to the <a href="/privacy" target="_blank">data</a> collected by all Test Pilot experiments, here are the key things you should know about what is happening when you use No More 404s:
  <ul>
  <li>We collect basic usage on how many times you encounter a Page Not Found error (code 404), how many times a cached version of that page exists from Archive.org, and how many times you choose to view the cached version.</li>
  <li>To provide cached versions of pages, we send 404 error page URLs to Archive.org. <a href="https://archive.org/" target=“_blank">Archive.org</a> discloses its privacy policy <a href="https://archive.org/about/terms.php" target="_blank">here</a>.</li>
  <li>We do not  collect  URLs of the pages you request or the URLs we send to Archive.org.</li>
  <li>We may share survey results you submit to us and aggregated telemetry data related to this experiment with the Internet Archive.</li>
  </ul>
```

We should use these in lieu of the single-liners we have now:

``` yaml
measurements: "In addition to the <a href=\"/privacy\" target=\"_blank\">data</a> collected by all Test Pilot experiments, here are the key things you should know about what is happening when you use No More 404s:\r\n<ul>\r\n<li>We collect basic usage on how many times you encounter a Page Not Found error (code 404), how many times a cached version of that page exists from Archive.org, and how many times you choose to view the cached version.</li>\r\n<li>To provide cached versions of pages, we send 404 error page URLs to Archive.org. <a href=\"https://archive.org/\" target=_blank\">Archive.org</a> discloses its privacy policy <a href=\"https://archive.org/about/terms.php\" target=\"_blank\">here</a>.</li>\r\n<li>We do not  collect  URLs of the pages you request or the URLs we send to Archive.org.</li>\r\n<li>We may share survey results you submit to us and aggregated telemetry data related to this experiment with the Internet Archive.</li>\r\n</ul>" 
```

### PR DESCRIPTION
**Pull request by pdehaan**
Fixes #1493

### CODE REVIEW

**Comment by chuckharmston** [comment]
Since `>` ignores newlines, can we use it to enforce an 80-char line limit?

**Comment by chuckharmston** [comment]
Might have to rebase, I merged #1490.

**Review by chuckharmston — CHANGES_REQUESTED** [review]
Since `>` ignores newlines, can we use it to enforce an 80-char line limit?

**Comment by pdehaan** [comment]
> Since `>` ignores newlines, can we use it to enforce an 80-char line limit?

I tried this w/ min-vid and am seeing some `\n` in the generated experiments.json:

#### Input:

``` yml
introduction: >
  <p>Love watching video? Love getting things done while you watch video? Try
    Min Vid. It’s like picture-in-picture where one picture is a video and the
    other is the entire Web.</p>
  <ul>
    <li><strong>Click and go:</strong> Pop up the Min Vid frame to keep videos
      playing in the foreground while you browse.</li>
    <li><strong>Put it where you want it:</strong> Min Vid lets you drag the
      video frame anywhere in the browser window.</li>
    <li><strong>Controls where you need them:</strong> Min Vid includes controls
      to let you pause/play, scrub, and adjust volume right in the frame.</li>
  </ul>
```

#### Output:

`"introduction": "<p>Love watching video? Love getting things done while you watch video? Try  Min Vid. It’s like picture-in-picture where one picture is a video and the\n  other is the entire Web.</p>\n<ul>  <li><strong>Click and go:</strong> Pop up the Min Vid frame to keep videos\n    playing in the foreground while you browse.</li>\n  <li><strong>Put it where you want it:</strong> Min Vid lets you drag the\n    video frame anywhere in the browser window.</li>\n  <li><strong>Controls where you need them:</strong> Min Vid includes controls\n    to let you pause/play, scrub, and adjust volume right in the frame.</li>\n</ul>\n",`

**Comment by chuckharmston** [comment]
> I tried this w/ min-vid and am seeing some \n in the generated experiments.json:

Right, that should be fine, so long as it isn't presented unescaped in the page, and doesn't inject `<br/>` or additional `<p>` tags.

**Comment by pdehaan** [comment]
r? @chuckharmston (or anybody else)

Once this lands, I may try my hand at refactoring the rats nest of avatar photos in #1496

**Review by chuckharmston — APPROVED** [review]

**Pull request merged**
