### PR TITLE
fix footer link alignment

### LINKED ISSUE #264: Footer looks vertically unbalanced
### Steps to reproduce:
1. Surf to http://idea-town-dev.elasticbeanstalk.com/home
2. Scroll to ze bottom.
3. Gasp dramatically.
### Actual results:

idea_town_and_change_experiment___django_site_admin_and_auto-tools_projects_mozbase_-_mozillawiki
**Figure 1:** Links in footer not centered vertically. I'm suspecting it's that suspect `padding: 4rem 0px 1rem;` rule. Things look subjectively better with `padding: 4rem 0`.
### Expected results:

idea_town_and_change_experiment___django_site_admin_and_auto-tools_projects_mozbase_-_mozillawiki

### PR DESCRIPTION
**Pull request by meandavejustice**
fixes #264

### CODE REVIEW

**Comment by pdehaan** [comment]
LGTM. :+1:
/ping @johngruen to give his feedback.

**Comment by johngruen** [comment]
@meandavejustice so this won't necessarily center the content b/c the container is flexed...let's make it so the footer content is tucked into the bottom of the page instead:

```
#main-footer {
  @include color-scheme($dark, $wash);
  @include flex-container(column, flex-end,  flex-start);
  border-top: 1px solid $default-dark;
  flex: 1 1;
  height: 100%;
  padding: 4rem 0 2rem;
```

**Comment by meandavejustice** [comment]
Thanks @johngruen. Got it updated.

**Comment by johngruen** [comment]
@meandavejustice crucial

**Pull request merged**
