### PR TITLE
Clarify the notification about locale availability

### LINKED ISSUE #2653: [l10n] Clarify the notification about locale availability
The current says:

`"This experiment is not supported in your language (ab_CD)"`

That could give the impression of lack of functionality in the localized browser. Could you change it to:

`"This experiment has not been yet translated to your language (ab_CD)"`

The "not yet" also hints at the possibility of contributing to the translation.

### PR DESCRIPTION
**Pull request by bidaian**
Fixes #2653

### CODE REVIEW

**Review by flodolo — CHANGES_REQUESTED** [review]
This code changes the FTL file but not the code calling it. I suggest to file an issue to also discuss the text to use more than a PR.

**Comment by flodolo** [comment]
Code calling the string is here
https://github.com/mozilla/testpilot/blob/b8e7a34b77f35cb281978a11e55521e5613ec5d0/frontend/src/app/containers/ExperimentPage.js#L172

CC @johngruen

**Comment by flodolo** [comment]
Background: https://groups.google.com/d/msg/mozilla.dev.l10n/bj69Is8w87E/UdgYr2iHBwAJ

**Comment by bidaian** [comment]
We can also check the code, but please note that even if we don't come up with a modification there, the wording might need some changes anyway. It is the same being used here:

`versionChangeNotice = {$experiment_title} **is not supported** in this version of Firefox.` --> please upgrade your Firefox

The "not supported" makes sense in versionChangeNotice. Not sure it's the best way to express the issue at hand here:

`localeUnavailableWarningTitle = This experiment **is not supported** in your language ({$locale_code}). ` --> please ... change your browser's language?

**Comment by flodolo** [comment]
I'm going to close this pull request, since it's not actionable, and focus the discussion in one place (the issue).

**Pull request closed without merging**
