### PR TITLE
feat(experiments): add xpi_url to Experiment model

### LINKED ISSUE #49: Add URL for addon XPI to Experiment data model
Need to add a URL for addon XPI, assuming they'll be uploaded to AMO and signed there.

We might want to consider supporting local uploads of XPIs in the future?

### PR DESCRIPTION
**Pull request by lmorchard**
- Add xpi_url URLField to Experiment model
- Schema migration for new DB column
- Update admin with xpi_url field
- Update API serializer with xpi_url field

Closes #49

### CODE REVIEW

**Comment by lmorchard** [comment]
Just the minimum here to add a new field pointing at the URL of an XPI for the experiment. More work to be done on front & back ends, but this is a start

**Comment by lmorchard** [comment]
Also, still kind of scratching my head at the Angular-style commit messages. Not sure what to stick in there for scope

**Comment by jaredhirsch** [comment]
@lmorchard lgtm :+1:

I'm puzzled by the scope thing, too; I half-jokingly resorted to `"*"` for my big first app PR out of desperation. Maybe we should change the gitcop settings?

**Comment by jaredhirsch** [comment]
We decided today that reviewer merges, so:

**Pull request merged**
