### PR TITLE
rename Idea Town to Test Pilot (part of #387)

### PR DESCRIPTION
**Pull request by clouserw**
This includes:
- Full rename.  I ran the project and clicked around and it worked
- I ran the backend tests, 100% pass
- I ran the frontend tests and saw a bunch of OKs and nothing that said failure, but it looks like maybe some tests didn't complete?  (They just said "Running...").  I don't know much about front-end tests so would like a review on those.

This does not include:
- a rebuilt add-on (the binary)
- we'll need to update travis-ci.org and coveralls when this lands
- This references idea-town.firefox.com and idea-town-dev.elasticbeanstalk.com.  I changed both to testpilot, but we should address those at some point
- This also references https://github.com/mozilla/idea-town-splash/ which is unchanged

### CODE REVIEW

**Comment by lmorchard** [comment]
Taking a peek

**Comment by pdehaan** [comment]
Need to fix the tox.ini to run flake8 against new /testpilot/ vs old /idea_town/ dir.

**Comment by lmorchard** [comment]
Hmm, looks like this is just a rename of the `idea_town` directory to `testpilot`.

We've got lots of references to `idea_town` / `idea-town` in `bin/*.sh`, `Gulpfile.js`, `manage.py`, etc.

FWIW, I ran this to try tracking down a bunch of things:

```
find . -not -path '*/.*/*' -type f -exec grep -Hnie 'idea.town' {} \;
```

That old name is pretty deeply rooted :/

**Comment by clouserw** [comment]
@pdehaan @lmorchard : doh, that's on me.  I was dividing and conquering and forgot to conquer the rest.  New patch soon.

**Comment by lmorchard** [comment]
Did another quick grep. Other than the coverage & travis-ci stuff already mentioned, there are just a handful of lingering references:

```
./.eslintrc:1:extends: idea-town
./.gitignore:16:idea_town/frontend/static/
./.gitignore:17:idea_town/frontend/static-src/vendor/
./.gitignore:18:idea_town/frontend/static-src/styles/vendor/
```

Nuking my docker containers to give this thing another round of testing on my machine...

**Comment by lmorchard** [comment]
Okay, finally rebuilt my Docker containers. Server-side tests all pass fine. `frontend_watcher_1` dies on the `.eslintrc` line because it's looking for `eslint-config-idea-town`

Speaking of which... do we need that eslint config in an external npm package? Could it be pulled into the project itself?

**Comment by clouserw** [comment]
Fixed those 3 dotfiles.  I'm not sure about the npm package.  @pdehaan maintains it, so he'd know best I think

**Comment by lmorchard** [comment]
Hmm, one last thing I think. I think this tweak will actually make this pass travis:

``` diff
diff --git a/addon/package.json b/addon/package.json
index ef6f95b..84f0284 100644
--- a/addon/package.json
+++ b/addon/package.json
@@ -25,7 +25,7 @@
     "babel-eslint": "^4.1.0",
     "eslint": "^1.2.1",
     "eslint-config-airbnb": "^0.0.8",
-    "eslint-config-testpilot": "^1.2.0",
+    "eslint-config-testpilot": "1.0.0",
     "jpm": "^1.0.1"
   },
   "preferences": [
```

Even with all the renaming, [it was just the addon part that failed](https://travis-ci.org/mozilla/idea-town/builds/108123719).

**Comment by lmorchard** [comment]
Oh, damn. [This looks like actual breakage in linting](https://travis-ci.org/mozilla/idea-town/jobs/108127087).

I see... this one spot has `isTestPilotAddonID` where everywhere else has `isTestpilotAddonID` (small p)

**Comment by pdehaan** [comment]
> Speaking of which... do we need that eslint config in an external npm package? Could it be pulled into the project itself?

re: "do we need that eslint config in an external package": Probably not, if all the repos have been merged into one uber-repo and we no longer need to share configs.

File a bug if you want me to merge the eslint-config-testpilot config back into the .eslintrc and I can handle that after we merge this PR. Should be a simple copy/paste, buy I'll have to look at the add-on module as well and make sure it doesnt cause breakage or duplication there.

**Comment by lmorchard** [comment]
Whoops! Just further broke this by merging a CSS fix. I think I'm going to do a quick rebase on it myself and merge it outside the PR, since it's 99.999% ready to go. Letting [travis tests run on my branch](https://travis-ci.org/lmorchard/idea-town/builds/108315397) and will merge once they pass.

**Comment by lmorchard** [comment]
Tweaked the case sensitive thing in the addon, rebased, tests pass

334d776393425df52564d9f1cad99c2b882ed736

**Comment by pdehaan** [comment]
Now that this has landed, should we rename this repo to /mozilla/testpilot?
It looks like our README badges are all broken because they're pointing to the new repo name.

**Comment by lmorchard** [comment]
@pdehaan: This stuff continues in #387 - there's renaming the repo, which then breaks a bunch of other things too.

**Comment by ghost** [comment]
Thanks @lmorchard and @pdehaan !

**Pull request closed without merging**
