### PR TITLE
Add endpoint for metrics

### PR DESCRIPTION
**Pull request by meandavejustice**
endpoint is at `/api/metrics`.

For our first run we will just push events to `datadog`. Going forward we can setup datadog's statsd integration.

### CODE REVIEW

**Comment by lmorchard** [comment]
So, I see I'm assigned, but I have some dumb questions: What's datadog & what are we doing with it? Do we have docs & issues & etc on it? I'm kind of light on context about this stuff.

**Comment by jaredhirsch** [comment]
@lmorchard So, cloud ops has been suggesting datadog (https://app.datadoghq.com) as a privacy/legal-approved third party metrics endpoint, mainly because it offers relatively simple dashboarding. They can give you an account if you need one (maybe ping mostlygeek). Firefox Accounts, WebPush, and some other services teams are using it, IIRC. We don't want datadog to receive any personally-identifiable information, which means that any metrics emitters need to sanitize locally before sending to the server (probably a good practice to get into).

Datadog isn't really well-documented anywhere, though there are references in the private mana wiki and on wikimo.

For the purposes of this bug, it's a place to put data. The long-term solution might well be to use S3 as the initial aggregation point, then use AWS lambda to do map-reducey things to it, and only direct things we want to visualize to dashboarding tools like datadog or even google analytics.

Does this help? Happy to attempt to provide more context

**Comment by jaredhirsch** [comment]
@mostlygeek This is a first metrics-to-datadog PR. Feedback welcome :-)

**Comment by lmorchard** [comment]
One top-of-head concern I've got about this API end point is that it looks like any rando can POST any random metric event. Might help to have a vocabulary of what we're collecting?

But then, I guess that just constrains the randos to submitting noise in the defined events. Hmm... maybe overthinking the concern here

**Comment by lmorchard** [comment]
<strike>We might want to add a `@login_required` to this API (however REST framework handles that, I'm not sure) and/or require a CSRF token, if only to toss in a speed bump on random spam bots mating with the metrics endpoint</strike>

Actually, [I think this is already in place](https://github.com/mozilla/idea-town/pull/78/files#diff-867a2641e83e4e2a804f960f368f4449R16) & I just missed it. So, like, you can ignore me and I think this looks fine. Getting hooked up with a datadog account, so hopefully I can give this API endpoint an actual drive around the block and just :+1: it.

**Comment by jaredhirsch** [comment]
> We might want to add a @login_required to this API (however REST framework handles that, I'm not sure) and/or require a CSRF token

Yeah, we've already got `csrftoken` and `sessionid` cookies set by Django, so maybe it'll just work. Looks like docs are here: http://www.django-rest-framework.org/api-guide/authentication/

**Comment by lmorchard** [comment]
Yeah, can confirm - POSTing as a rando to the endpoint gets rejected:

```
➜  idea-town git:(4495f00) ✗ curl -ksi -D'{ "title": "foo", "bar": "baz" }' -XPOST http://ideatown.dev:8000/api/metrics
HTTP/1.0 403 FORBIDDEN
```

**Comment by meandavejustice** [comment]
@lmorchard moved to using `import datadog` as you suggested.

**Comment by lmorchard** [comment]
So, after sorting our my datadog & CSRF token business, it looks like this does a thing for me! My last question is... does datadog have a view somewhere that I can see what I POST'd?

```
➜  idea-town git:(4495f00) ✗ curl -ksi -H 'X-CSRFToken: VVgoSjG9NKSjzLm6VTv1UefE8eRgfLEZ' -H "Cookie: csrftoken=VVgoSjG9NKSjzLm6VTv1UefE8eRgfLEZ; sessionid=w7o7tanryoxjg2034507242e1tgxyzlj" -H "Accept: text/html,application/json" -H "Content-Type: application/json"   -d'{ "title": "idea-town-foo", "bar": "baz" }' -XPOST http://ideatown.dev:8000/api/metrics/ | more
HTTP/1.0 200 OK
Date: Wed, 23 Sep 2015 18:37:41 GMT
Server: WSGIServer/0.2 CPython/3.4.3
Vary: Accept, Cookie
X-Frame-Options: SAMEORIGIN
Allow: GET, POST, HEAD, OPTIONS
Content-Type: application/json

{"created":"2015-09-23T18:37:41.444044","title":"idea-town-foo","bar":"baz"}
```

**Comment by lmorchard** [comment]
Eh, going to say this is good, and we can keep refining it with actual usage

**Comment by meandavejustice** [comment]
@lmorchard here is the main event stream I've been using to debug https://app.datadoghq.com/event/stream?tags_execution=and&show_private=true&per_page=30&aggregate_up=true&use_date_happened=false&display_timeline=true&from_ts=1442448000000&is_zoomed=false&to_ts=1443052800000&is_auto=false&incident=true&only_discussed=false&no_user=false&page=0&live=true&bucket_size=10800000

**Comment by mostlygeek** [comment]
Looks ok. I would suggest using tags on your event metrics so they can be filtered/found/correlated with the stastd information into a dashboard later. 

Did you guys commit real api keys into the code?

**Pull request merged**
