### PR TITLE
Fixes #3751 [Experiment details] The "Your privacy" button is now showing in experiment controls area on 3rd party browsers.

### LINKED ISSUE #3751: [Experiment details] The "Your privacy" button is missing from experiment controls area on 3rd party browsers
**[Affected versions]:**
- All 3rd party browsers

**[Affected Platforms]:**
- All Windows
- All MacOS
- All Linux

**[Steps to reproduce]:**
1. Open a 3rd party browser and navigate to https://testpilot.dev, mozaws.net page.
2. Scroll down on the page and click on any experiment card available except "Side View".
3. Look for "Your privacy" blue text button under the experiment logo or experiment control buttons.
4. Return to Homepage and click on "Side View" experiment card.
5. Look for the same "Your privacy" blue text button.

**[Expected result]:**
- All experiments, including "Side View" have the "Your privacy"  blue text button displayed under the experiment logo or experiment control buttons.

**[Actual result]:**
- Side View experiment does not have the "Your privacy" button displayed.

**[Notes]:**
- This issue occurs probably because the privacy button is bundled with the experiment control buttons and Side View has none displayed due to experiment type.
- Here is a screen recording of the issue: https://goo.gl/iDvL9o

### PR DESCRIPTION
**Pull request by KhushilMistry**
Fixes #3751 [Experiment details] The "Your privacy" button is now showing in experiment controls area on 3rd party browsers.

screen shot 2018-09-25 at 1 43 25 pm

screen shot 2018-09-25 at 1 43 43 pm

screen shot 2018-09-25 at 1 44 06 pm

### CODE REVIEW

**Comment by meandavejustice** [comment]
I think in the case of 3rd party browsers, "Your Privacy" should be in the bullet point list instead of floating in place of the button. cc/ @youwenliang @johngruen

**Comment by meandavejustice** [comment]
ping @youwenliang

**Comment by youwenliang** [comment]
> I think in the case of 3rd party browsers, "Your Privacy" should be in the bullet point list instead of floating in place of the button. cc/ @youwenliang @johngruen

Without the action button, I agree that we should put "Your privacy" in the bullet list.

**Comment by KhushilMistry** [comment]
Okay. I will update my PR and ping here.

**Comment by KhushilMistry** [comment]
Checked on Google Chrome.

screenshot 2018-10-24 at 1 11 44 am

screenshot 2018-10-24 at 1 11 53 am

**Comment by meandavejustice** [comment]
@KhushilMistry Looks like tests are failing because of some [flow errors](https://flow.org/). You can run the flow checker locally with `npm run flow`. also `npm run lint` for linting, and `npm run tests` for unit tests

**Comment by KhushilMistry** [comment]
@meandavejustice Sorry for multiple commits. I was doing silly mistakes. Now its ready for review.

**Pull request merged**
