### PR TITLE
Apply Photon Styles to Experiment Details Pages

### LINKED ISSUE #2962: Apply Photon Styles to Experiment Details Pages
Please see the following spec:

https://mozilla.github.io/testpilot-assets/Test_Pilot_Website/01_Measurements/Detailpage_20170927/

We could break this down more if necessary but the changes on this page are relatively minor

### PR DESCRIPTION
**Pull request by lmorchard**
Spec:
https://mozilla.github.io/testpilot-assets/Test_Pilot_Website/01_Measurements/Detailpage_20170927/

- Tweaked base font size & line height for site, since it seemed to so
  commonly repeat in the spec

- General tweaks to font sizes and element spacings

- Smaller experiment thumbnail icon

- Added stories and sample data for DetailsHeader component

- Move ExperimentPage styles into the component bundle directory

- GraduatedNotice style tweaks

- Move ExperimentPlatforms into its own component directory, move in
  styles & image assets

- Tweaks to Copter component for new size in banner

- Small tweaks to resolve sass-lint warnings

- Added Fira Sans Book fonts missing from fira.css on CDN but used in
  specs

- Constants for common font-weights, corresponding to Fira Sans faces

Fixes #2962

### CODE REVIEW

**Comment by lmorchard** [comment]
Kind of getting in over my head on this one, style-wise. Lots of little changes all over the place. Could probably use some further tweaks & DRYing out.

**Comment by lmorchard** [comment]
Also looks like this is going to collide a bit with PR #3031, so I might try splicing out the parts that mess with the big promo at the top when the add-on isn't installed

**Comment by MozillaTestPilotStorybook** [comment]
# Storybook Deployment
Pull Request: http://testpilot-storybook.dev.mozaws.net/pull/3038/index.html
Commit: http://testpilot-storybook.dev.mozaws.net/51a8f40701a41872a1449c9d7d4e5943c172520c/

**Comment by johngruen** [comment]
@lmorchard i'll review and merge this then get to work rebasin' my dumb thing :)

**Comment by lmorchard** [comment]
My sass-fu is bad, so feel free to point & laugh

**Comment by johngruen** [comment]
@lmorchard it actually looks like we're gonna get a 3 way conflict with #3037. Let's figure out a plan in our meeting today.

**Comment by lmorchard** [comment]
Rebased against master & resolved conflicts

**Comment by MozillaTestPilotStorybook** [comment]
# Storybook Deployment
Pull Request: http://testpilot-storybook.dev.mozaws.net/pull/3038/index.html
Commit: http://testpilot-storybook.dev.mozaws.net/8949080cbc3357b1357c98f4be1e54e1511f2533/

**Comment by fzzzy** [comment]
I've tested this out and it looks good. @johngruen will also be giving it a look when he rebases and fixes conflicts with his branch tomorrow.

**Pull request merged**
