### PR TITLE
add lang param to footer email

### PR DESCRIPTION
**Pull request by johngruen**
#1989

### CODE REVIEW

**Comment by chuckharmston** [comment]
Note that this doesn't include the modal email form; see #1758.

**Comment by chuckharmston** [comment]
Needs tests.  😑

**Comment by johngruen** [comment]
@chuckharmston that got fixed here #1987 (re your first comment)

**Comment by chuckharmston** [comment]
You'll need to add `locale` to `View.propTypes`, `NewsletterFooter.propTypes`, and `NewsletterForm.propTypes`.

**Comment by johngruen** [comment]
@chuckharmston should i set a default?

**Comment by chuckharmston** [comment]
> @chuckharmston should i set a default?

Nah, just make sure it's a required prop; it should be [set automatically](https://github.com/mozilla/testpilot/blob/a4b08eaafefe15db6720ce3b8b0eba2952ca240b/frontend/src/app/reducers/browser.js#L9).

Speaking of that bit, it's mutating `navigator.language`. What does Basket want out of this? It may be that instead of using a prop, we should use `(navigator.language || '')`.

**Comment by chuckharmston** [comment]
Tests look fine ~; pending the screenshot I requested in IRC~, r+wc

**Pull request merged**
