### PR TITLE
Move experiment controls

### LINKED ISSUE #3503: Move Experiment Controls to Sidebar
In order to simplify the layout of experiment detail pages and accommodate a wider variety of buttons, we should move the experiment controls to the sidebar per the below spec:

https://mozilla.github.io/testpilot-assets/Test_Pilot_Website/01_Measurements/Mobile_experiment_integration/#artboard8

https://mozilla.github.io/testpilot-assets/Test_Pilot_Website/01_Measurements/Mobile_experiment_integration/#artboard5

Please note the experiment platform details will now sit where the experiment controls used to be

### PR DESCRIPTION
**Pull request by dannycoates**
fixes #3503

screen shot 2018-05-01 at 12 23 51 pm
screen shot 2018-05-01 at 1 12 19 pm
screen shot 2018-05-01 at 1 12 46 pm
screen shot 2018-05-01 at 1 13 15 pm
screen shot 2018-05-01 at 1 14 22 pm
screen shot 2018-05-01 at 1 15 35 pm

### CODE REVIEW

**Comment by MozillaTestPilotStorybook** [comment]
# Storybook Deployment
Pull Request: http://testpilot-storybook.dev.mozaws.net/pull/3517/index.html
Commit: http://testpilot-storybook.dev.mozaws.net/dbd7d9586aaec81c966da9cbcc1b1246e509ecd8/

**Comment by MozillaTestPilotStorybook** [comment]
# Storybook Deployment
Pull Request: http://testpilot-storybook.dev.mozaws.net/pull/3517/index.html
Commit: http://testpilot-storybook.dev.mozaws.net/9fac21bd13e7a83796d58d885d559bc6f8ceb18f/

**Comment by MozillaTestPilotStorybook** [comment]
# Storybook Deployment
Pull Request: http://testpilot-storybook.dev.mozaws.net/pull/3517/index.html
Commit: http://testpilot-storybook.dev.mozaws.net/83a6f6c8a3bcac6a6201615d2d062df10bb57717/

**Comment by MozillaTestPilotStorybook** [comment]
# Storybook Deployment
Pull Request: http://testpilot-storybook.dev.mozaws.net/pull/3517/index.html
Commit: http://testpilot-storybook.dev.mozaws.net/e5b91caa9877b2907094d1d1f23f7445a9504e56/

**Comment by MozillaTestPilotStorybook** [comment]
# Storybook Deployment
Pull Request: http://testpilot-storybook.dev.mozaws.net/pull/3517/index.html
Commit: http://testpilot-storybook.dev.mozaws.net/0287de0395861ad6187448830b117eaa3f9f9ddd/

**Comment by MozillaTestPilotStorybook** [comment]
# Storybook Deployment
Pull Request: http://testpilot-storybook.dev.mozaws.net/pull/3517/index.html
Commit: http://testpilot-storybook.dev.mozaws.net/457bede7b8cc3ca2dd69fffd3711c6979135b2d0/

**Comment by MozillaTestPilotStorybook** [comment]
# Storybook Deployment
Pull Request: http://testpilot-storybook.dev.mozaws.net/pull/3517/index.html
Commit: http://testpilot-storybook.dev.mozaws.net/8ab55b27c0ece16d908d86f556149668e3921cf1/

**Comment by MozillaTestPilotStorybook** [comment]
# Storybook Deployment
Pull Request: http://testpilot-storybook.dev.mozaws.net/pull/3517/index.html
Commit: http://testpilot-storybook.dev.mozaws.net/cdfcb29db8b8f3708a713442bb7caa9cc4ba8829/

**Review by sevaan — COMMENTED** [review]
Looks great, visually! Thanks Danny!

**Comment by dannycoates** [comment]
redesign changes coming

**Comment by MozillaTestPilotStorybook** [comment]
# Storybook Deployment
Pull Request: http://testpilot-storybook.dev.mozaws.net/pull/3517/index.html
Commit: http://testpilot-storybook.dev.mozaws.net/f34c010cbad8b819edeb5ed333ba54f16b19e44e/

**Comment by dannycoates** [comment]
new spec: https://mozilla.github.io/testpilot-assets/Test_Pilot_Website/01_Measurements/circle_header/

**Comment by MozillaTestPilotStorybook** [comment]
# Storybook Deployment
Pull Request: http://testpilot-storybook.dev.mozaws.net/pull/3517/index.html
Commit: http://testpilot-storybook.dev.mozaws.net/7ce986008f74d101a287abcb6811030d1ff04542/

**Comment by dannycoates** [comment]
screen shot 2018-05-01 at 1 46 16 pm

adjusted circle size and legal links

**Comment by MozillaTestPilotStorybook** [comment]
# Storybook Deployment
Pull Request: http://testpilot-storybook.dev.mozaws.net/pull/3517/index.html
Commit: http://testpilot-storybook.dev.mozaws.net/4959f238ab398747da3c0dd2df9e4ec20c1b885b/

**Comment by MozillaTestPilotStorybook** [comment]
# Storybook Deployment
Pull Request: http://testpilot-storybook.dev.mozaws.net/pull/3517/index.html
Commit: http://testpilot-storybook.dev.mozaws.net/7fca577e750cee8d6adb2059248b8ea07ab510b3/

**Comment by MozillaTestPilotStorybook** [comment]
# Storybook Deployment
Pull Request: http://testpilot-storybook.dev.mozaws.net/pull/3517/index.html
Commit: http://testpilot-storybook.dev.mozaws.net/6c7823c8e1af54b401902ff1fa113aa2124bedf9/

**Comment by johngruen** [comment]
More circle!

**Comment by johngruen** [comment]
@sevaan i still kinda feel like the experiment start date/link list is too big/too densely packed together

**Comment by johngruen** [comment]
also @dannycoates, I also think the `Your privacy` link should be right below the primary buttons...

also also, and this is maybe an extra nit, but i think we should make all the sidebar actions like `Launch Tour` and `Experiment Start Date` to be `Launch tour` and `Experiment start date`...I don't think we need to make new strings or localize the capitalization change.

**Review by johngruen — CHANGES_REQUESTED** [review]
Added some review in comments

**Comment by sevaan** [comment]
> @sevaan i still kinda feel like the experiment start date/link list is too big/too densely packed together

@dannycoates Let's make the section headings in the side nav (e.g. Start Date, "Brought to you by") 21px and see how it feels.

As for Your Privacy, I think we can just use the same formatting of the fine print on the dual install button, and put it there.

image

**Review by meandavejustice — APPROVED** [review]
Looks great to me, once the latest changes to start date are fixed and conflicts resolved, I'm good to merge.

**Review by flodolo — APPROVED** [review]
For the record, I'm fine with changing capitalization without new IDs.

**Comment by dannycoates** [comment]
screen shot 2018-05-02 at 9 19 26 am

**Comment by MozillaTestPilotStorybook** [comment]
# Storybook Deployment
Pull Request: http://testpilot-storybook.dev.mozaws.net/pull/3517/index.html
Commit: http://testpilot-storybook.dev.mozaws.net/292d216019f15f8b41a556859f910bec091447d0/

**Review by johngruen — APPROVED** [review]

**Comment by johngruen** [comment]
Ditch the colon?

**Comment by dannycoates** [comment]
It looks weird without the colon when it doesn't wrap. I took the font down to 20px.
screen shot 2018-05-02 at 12 21 00 pm

**Comment by MozillaTestPilotStorybook** [comment]
# Storybook Deployment
Pull Request: http://testpilot-storybook.dev.mozaws.net/pull/3517/index.html
Commit: http://testpilot-storybook.dev.mozaws.net/0166a33ad9ab6dd0b55cf1f561d342ea43fffe59/

**Comment by sevaan** [comment]
That looks good to me. But broader q that might help with preventing wrapping on other locales: do we need the word "Experiment"? I feel like "Start Date" might suffice.

**Comment by dannycoates** [comment]
> do we need the word "Experiment"? I feel like "Start Date" might suffice.

it would suffice, but I don't want to change the string

**Comment by MozillaTestPilotStorybook** [comment]
# Storybook Deployment
Pull Request: http://testpilot-storybook.dev.mozaws.net/pull/3517/index.html
Commit: http://testpilot-storybook.dev.mozaws.net/9e7593054935b93f49bb5b5fa74856e77a59a499/

**Comment by SoftVision-PaulOiegas** [comment]
I personally think the large rectangular logo + a contained area for the buttons as initially designed in #3503 would have looked better... Also, there is now a discrepancy between the desktop and mobile look of the website, since we have a rectangular logo on mobile (which looks awesome).

However, if it will remain like this, can we have at least the legal string under the install button on a  different background color ([as initially proposed](https://user-images.githubusercontent.com/473531/39444348-659d8bd8-4c85-11e8-8080-10ccb7925750.png))? It looks pretty awkward on white, like it needs anti-aliasing...

**Comment by sevaan** [comment]
The problem with that big box is it pushed the buttons much lower on the page than they should be, for key pieces of functionality. By reducing hte header, the buttons are brought up higher and are made more visible.

> like it needs anti-aliasing...

@jgruen We were chatting about Fire font issues on the Test Pilot site...this appears to be another one.
What do you think of switching to Open Sans? Other Mozilla properties use it, it has a little bit of character similar to Fira, but I believe it is much more readable.

**Comment by SoftVision-PaulOiegas** [comment]
> The problem with that big box is it pushed the buttons much lower on the page than they should be, for key pieces of functionality. By reducing hte header, the buttons are brought up higher and are made more visible.

Then it was the right call.

**Comment by jgruen** [comment]
@sevaan I'm pretty sure you meant @johngruen, not @jgruen...

**Comment by MozillaTestPilotStorybook** [comment]
# Storybook Deployment
Pull Request: http://testpilot-storybook.dev.mozaws.net/pull/3517/index.html
Commit: http://testpilot-storybook.dev.mozaws.net/9fac21bd13e7a83796d58d885d559bc6f8ceb18f/

**Comment by MozillaTestPilotStorybook** [comment]
# Storybook Deployment
Pull Request: http://testpilot-storybook.dev.mozaws.net/pull/3517/index.html
Commit: http://testpilot-storybook.dev.mozaws.net/9fac21bd13e7a83796d58d885d559bc6f8ceb18f/

**Pull request merged**
