### PR TITLE
Drop HTML from the tour steps L10n

### PR DESCRIPTION
**Pull request by clouserw**
This patch is a lot smaller than it looks.  Mostly it's L10n files.

hat-tip to @chuckharmston for his original work in #1782

### CODE REVIEW

**Comment by johngruen** [comment]
@clouserw can we get a screenshot here

**Comment by ghost** [comment]
page-shot-2017-1-17 firefox test pilot - min vid

**Comment by johngruen** [comment]
looks dope

**Comment by johngruen** [comment]
R+ pending rebase

**Pull request merged**
