### PR TITLE
Fix Color reference in Email Tabs experiment

### LINKED ISSUE #3984: [Experiment details] Email Tabs page wrongly mentions "Firefox Color" in the legal string under the green install button
Issue found by @flodolo and mentioned on Slack. Logging it on his behalf.

**[Affected versions]:**
- Firefox 63.0.1 and above

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Steps to reproduce]:**
- Test Pilot is not installed on the used profile.

**[Steps to reproduce]:**
1. Open Firefox browser with the profile from prerequisites and navigate to https://testpilot.firefox.com page.
2. Scroll down to the available experiments cards and click on the "Email Tabs" one.
3. Observe the privacy and legal notice strings under the "Install Test Pilot & Enable Email Tabs" green button on the left.
 
**[Expected result]:**
- The "By proceeding, you agree to the terms and privacy policies of Test Pilot and the Email Tabs privacy policy." string is displayed.

**[Actual result]:**
- The string wrongly mentions the "Firefox Color" instead of Email Tabs privacy policy.

**[Notes]:**
- it seems that just the string has this issue since the link underneath correctly scrolls down to the Email Tabs Privacy notice. 
- Here is a screenshot of the issue: 

d4c833d3-7c9a-43ad-baee-09d36289c9bb

### PR DESCRIPTION
**Pull request by devinreams**
Fixes #3984

### CODE REVIEW

**Comment by flodolo** [comment]
There's a risk that we already have wrong translations around. The only way to fix that would be to change the string ID.

**Comment by devinreams** [comment]
>There's a risk that we already have wrong translations around.

@flodolo Yes, I saw just [a few translations came in from Pontoon](https://github.com/mozilla/testpilot/compare/l10n) but I could easily find/replace that instead of prompting re-translations since its just a product name swap out. What do you think?

**Comment by flodolo** [comment]
> @flodolo Yes, I saw just [a few translations came in from Pontoon](https://github.com/mozilla/testpilot/compare/l10n) but I could easily find/replace that instead of prompting re-translations since its just a product name swap out. What do you think?

That works for me. Let me know if there are some that you don't feel comfortable in touching

**Comment by SoftVision-PaulOiegas** [comment]
Just checked locally and it looks ok on the front end.

**Comment by pdehaan** [comment]
<details>
<summary><strike>And the few other instances in the other locales:</strike> Already fixed!</summary>

```sh
$ git grep "emailtabsLegalnotice = " locales/*/experiments.ftl | grep "Firefox Color"

locales/cy/experiments.ftl:emailtabsLegalnotice = Wrth fynd ymlaen, rydych chi'n cytuno ar y termau <terms-link> terms </ terms-link> a <privacy-link> privacy </ privacy-link> polisïau Prawf Peilot a'r polisi preifatrwydd <modal-link> Firefox Color </ modal -link>.
locales/de/experiments.ftl:emailtabsLegalnotice = Indem Sie fortfahren, stimmen Sie den <terms-link>Nutzungsbedingungen</terms-link> und der <privacy-link>Datenschutzerklärung</privacy-link> von Test Pilot sowie der <modal-link>Datenschutzerklärung von Firefox Color</modal-link> zu.
locales/en-CA/experiments.ftl:emailtabsLegalnotice = By proceeding, you agree to the <terms-link>terms</terms-link> and <privacy-link>privacy</privacy-link> policies of Test Pilot and the <modal-link>Firefox Color privacy policy</modal-link>.
locales/en-US/experiments.ftl:emailtabsLegalnotice = By proceeding, you agree to the <terms-link>terms</terms-link> and <privacy-link>privacy</privacy-link> policies of Test Pilot and the <modal-link>Firefox Color privacy policy</modal-link>.
locales/es-AR/experiments.ftl:emailtabsLegalnotice = Al continuar, acepta los términos <terms-link> </terms-link> y <privacy-link> las políticas de privacidad </privacy-link> de Test Pilot y la <modal-link> política de privacidad de Firefox Color  </modal -link>.
locales/ka/experiments.ftl:emailtabsLegalnotice = გაგრძელების შემთხვევაში, თქვენ ეთანხმებით Test Pilot-ის <terms-link>გამოყენების პირობებსა</terms-link> და <privacy-link>პირადულობის</privacy-link> დებულებებს, აგრეთვე <modal-link>Firefox Color-ის პირადულობის დებულებას</modal-link>.
locales/ms/experiments.ftl:emailtabsLegalnotice = Dengan meneruskan, anda bersetuju dengan <terms-link>terma</terms-link> dan polisi <privacy-link>privasi</privacy-link> Test Pilot dan <modal-link>polisi privasi Firefox Color</modal-link>.
locales/nl/experiments.ftl:emailtabsLegalnotice = Door verder te gaan, gaat u akkoord met de <terms-link>voorwaarden</terms-link> en beleidsregels voor <privacy-link>privacy</privacy-link> van Test Pilot en het <modal-link>privacybeleid van Firefox Color</modal-link>.
```
</details>

<br>

And now I'm noticing some odd closing tags like `</ modal -link>` in some cases. Not sure how to check globally for those, or if they're even broken in the front end for those locales.

**Comment by devinreams** [comment]
>That works for me. Let me know if there are some that you don't feel comfortable in touching

@flodolo Some translators were kind enough to catch our mistake and change it in the translation, the rest are confidently replaced in this PR. ⭐️ 

>Just checked locally and it looks ok on the front end.

Thanks for the help @SoftVision-PaulOiegas and @flodolo. 🏅

**Comment by flodolo** [comment]
> @flodolo Some translators were kind enough to catch our mistake and change it in the translation, the rest are confidently replaced in this PR. ⭐️

Yes, they are also the ones who spotted it in the first place, I'm just the messenger.

**Review by flodolo — APPROVED** [review]

**Comment by devinreams** [comment]
>And now I'm noticing some odd closing tags like </ modal -link> in some cases. Not sure how to check globally for those, or if they're even broken in the front end for those locales.

@pdehaan Yeah I saw those too. They don't _seem_ to cause issues as confirmed with es-AR 😅 

screen shot 2018-11-13 at 11 21 45 am

**Comment by pdehaan** [comment]
> And now I'm noticing some odd closing tags like `</ modal -link>` in some cases. Not sure how to check globally for those, or if they're even broken in the front end for those locales.

Possibly closer to a solution, although very ignorant greppin' on my part:

```sh
$ git grep "<modal-link>" locales/*/experiments.ftl | grep -v "</modal-link>"

# `</ terms-link>`, `</ privacy-link>`, and `</ modal -link>`:
1. locales/cy/experiments.ftl:emailtabsLegalnotice = Wrth fynd ymlaen, rydych chi'n cytuno ar y termau <terms-link> terms </ terms-link> a <privacy-link> privacy </ privacy-link> polisïau Prawf Peilot a'r polisi preifatrwydd <modal-link> Email Tabs </ modal -link>.

# `</ terms-link>`, `</ privacy-link>`, and `</ modal -link>`:
2. locales/cy/experiments.ftl:pricewiseLegalnotice = Drwy barhau, rydych chi'n cytuno i<terms-link>delerau</ terms-link> a pholisiau<privacy-link> preifatrwydd</ privacy-link> Test Pilot a pholisi preifatrwydd <modal-link>Price Wise</ modal -link>.

# Empty `<terms-link> </terms-link>`, and `</modal -link>`:
3. locales/es-AR/experiments.ftl:emailtabsLegalnotice = Al continuar, acepta los términos <terms-link> </terms-link> y <privacy-link> las políticas de privacidad </privacy-link> de Test Pilot y la <modal-link> política de privacidad de Email Tabs  </modal -link>.

# Empty `<terms-link> </terms-link>`, and `</ modal-link>`:
4. locales/es-AR/experiments.ftl:pricewiseLegalnotice = Al continuar, estás aceptando los términos <terms-link> </terms-link> y <privacy-link> privacidad </privacy-link> de las políticas de Test Pilot y la <modal-link> política de privacidad de Price Wise </ modal-link>.

# Invalid `<terms-link>términos</>`, and `<privacy-link>privacidad</terms-link>`, and `<modal-link>Políticas de privacidad de Notes</privacy-link>`:
5. locales/es-MX/experiments.ftl:notesLegalnoticeWithlinks = Al proceder, aceptas los <terms-link>términos</> y las políticas de <privacy-link>privacidad</terms-link> de Test Pilot y la <modal-link>Políticas de privacidad de Notes</privacy-link>.

# `</ terms-link>`, `</ privacy-link>`, and `</ modal -link>`:
6. locales/nl/experiments.ftl:pricewiseLegalnotice = Door verder te gaan, gaat u akkoord met de <terms-link>voorwaarden</ terms-link> en beleidsregels voor <privacy-link>privacy</ privacy-link> van Test Pilot en het <modal-link>privacybeleid van Price Wise</ modal -link>.
```

---

**UPDATE:** Submitted as #3986

**Pull request merged**
