### PR TITLE
Update sample data documentation.

### PR DESCRIPTION
**Pull request by chuckharmston**
I was getting odd tracebacks about 50% of the time after running `loaddata`. I get them 0% of the time if restarting after running `loaddata`.

### CODE REVIEW

**Comment by lmorchard** [comment]
What were the tracebacks? Might be something else worth fixing.

**Comment by chuckharmston** [comment]
Seems like it was a recurrence of the timing issues we've had previously; the frontend code hadn't finished building yet.

**Comment by lmorchard** [comment]
Hmm, this could be something we want to fix in either Gulp or Django or both. Gulp runs "clean" on every file change, which deletes everything & starts from scratch. Django throws errors when static files linked to using `static()` are missing. So, Django tracebacks while Gulp is building. :(

**Comment by chuckharmston** [comment]
Yeah, exactly.

I'm not sure what a fix would look like, but it certainly isn't this PR.

**Pull request closed without merging**
