### PR TITLE
(do not merge) Try updating package-lock.json

### PR DESCRIPTION
**Pull request by lmorchard**
[As a follow up to my comment in #3798](https://github.com/mozilla/testpilot/issues/3798#issuecomment-413905493), I'm to give updating `package-lock.json` a try. CircleCI should build the site in tests for this PR, and I'll take a look at the `frontend.zip` artifact to see if that build has lost images. If not, then I guess this PR is safe to merge. But, to be safe, don't merge until then

### CODE REVIEW

**Comment by MozillaTestPilotStorybook** [comment]
# Storybook Deployment
Pull Request: http://testpilot-storybook.dev.mozaws.net/pull/3802/index.html
Commit: http://testpilot-storybook.dev.mozaws.net/6281dcfa82ce22c37ca8f3f87503c1d04d6c0192/

**Comment by lmorchard** [comment]
Oh wait, I totally missed PR #3801 - that's basically the same thing as this. I may delete this PR.

**Comment by devinreams** [comment]
Yours here touched a whole lot more lines (approx. 100x more) than mine, hmm...

My other branch is also just playing around to update dependencies to see if that kicks the package and package lock to get closer to the same place (and avoid this weird issue we hit with package not being informed enough to get a running site built).

So in my mind this PR seems more atomic and useful to merge...

**Comment by lmorchard** [comment]
> Yours here touched a whole lot more lines (approx. 100x more) than mine, hmm...

Yeah, not sure what's up with that other than that package-lock.json is a really terrible format for diffs.

Just to be sure, I tried two `npm installs` from the `package-lock.json` on master using Bash on Windows and got the same changes as in this PR, so it's at least stable / deterministic on my machine. 

That said... I'm *still* not reproducing the problem with images

**Comment by devinreams** [comment]
>That said... I'm still not reproducing the problem with images

Even if you remove your "node_modules" and "package-lock.json" files and then `npm install`? Images work A-OK for you still then? 😮

**Pull request closed without merging**
