### PR TITLE
Fix #2958 Photonize newsletter footer

### LINKED ISSUE #2958: Apply Photon Styles To Email Footer
Please see the following Spec:

https://mozilla.github.io/testpilot-assets/Test_Pilot_Website/01_Measurements/Homepage_20170927/#artboard6

@ChenMorpheus can you make sure we have the appropriate email icon asset.

### PR DESCRIPTION
**Pull request by fzzzy**
- Componentize NewsletterFooter and NewsletterForm
- Add stories for same
- Switch to new svg icon
- Switch to svg checkboxes with new style
- Change styles to match spec provided in #2958

### CODE REVIEW

**Comment by fzzzy** [comment]
Hmm looks like I forgot to update the error message style.

**Comment by fzzzy** [comment]
@johngruen The spec calls for the error box to have a little downward pointing arrow, any idea how I should implement that?

https://mozilla.github.io/testpilot-assets/Test_Pilot_Website/01_Measurements/Homepage_20170927/#artboard6

(At the bottom where it says "There was an error [...]")

**Comment by johngruen** [comment]
@fzzzy try this: https://css-tricks.com/snippets/css/css-triangle/ but do it with the `::after` psuedo-selector

**Comment by fzzzy** [comment]
@johngruen Thanks!

**Comment by fzzzy** [comment]
We're actually using the built-in browser email validation ui, so we don't have control over what it looks like. It looks pretty similar to the mockup. This pr is ready to be reviewed now.

**Comment by johngruen** [comment]
@fzzzy can you run svgo on the svgs you added and also make a new PR into this repo (not your fork) so we can get the storybook server built?

**Comment by fzzzy** [comment]
@johngruen Done https://github.com/mozilla/testpilot/pull/3030

**Pull request closed without merging**
