### PR TITLE
Update docs on new static generation dev server

### LINKED ISSUE #1350: Update docs to describe new static generation & React architecture
It's all still kind of a mystery. And not the good kind.

### PR DESCRIPTION
**Pull request by lmorchard**
Fixes #1350 

Some cleanup in advance - once we remove Django completely, the coverage & dependencies badges won't be relevant anymore. Maybe we want to set up equivalents for Node, but that's out of scope for this PR.

This doesn't say anything about how the React stuff goes together, either. That seems like a way bigger doco project.

### CODE REVIEW

**Review by chuckharmston — CHANGES_REQUESTED** [review]
This looks great.

One ask: that we document somewhere how we generate `index.html` files for each of that routes separate from the router.

**Comment by lmorchard** [comment]
@chuckharmston - I can work on adding more in-depth docs on the static generation stuff and React, but I was trying to keep this PR limited to just talking about how to get the new server running:

> This doesn't say anything about how the React stuff goes together, either. That seems like a way bigger doco project.

**Review by chuckharmston — APPROVED** [review]

**Comment by chuckharmston** [comment]
That's fine, approved.

**Comment by lmorchard** [comment]
Also rebasing this and changing the commit comment from "fixes #1350" to "issue #1350" - because given the above caveats, there's still work to be done!

**Pull request merged**
