### PR TITLE
CHORE: resize avatars

### PR DESCRIPTION
**Pull request by CHBaker**
Resize all avatars from the experiments directory for consistency.

- Size: 64x64 pixels
- Passes all tests

addresses: #1845

### CODE REVIEW

**Comment by johngruen** [comment]
@CHBaker hey, thanks for knocking this out...i'm guessing you did it with a script?

If so, I think we should probably do everything at 112px x 112px and then use width and height attrs in HTML to set images to 64 x 64 and browsers handle downsampling the images. This should work better for Retina/HiDPI displays.

**Comment by CHBaker** [comment]
Yes @johngruen I can change them to 112x112 px, and I only just started contributing here so I'm not sure what files the images are sized to the html, if you point that out i'll get it taken care of

**Comment by johngruen** [comment]
@CHBaker I commented on the original bug, sorry @pdehaan and I have been giving you conflicting info here :(

**Comment by lmorchard** [comment]
Are there pending next steps to wrap up this PR? Or can we merge it?

**Comment by CHBaker** [comment]
@lmorchard  These are good to merge, all images are 112px by 112px

**Comment by meandavejustice** [comment]
Pulled this down _just to be sure_ and it's looking good. Can you squash these commits into one @CHBaker, then we should be good to merge

**Comment by chuckharmston** [comment]
@meandavejustice we can squash from here! On it. Thanks for the contribution @CHBaker!

**Pull request merged**
