### PR TITLE
remove querystring gateway for public launch (okay to merge after review)

### LINKED ISSUE #688: Remove ?butimspecial query string gate
Ref: #605 

@javaun can we bring this down ahead of our Monday deployment? Our next is scheduled ~Wednesday/Thursday.

### PR DESCRIPTION
**Pull request by meandavejustice**
- fixes #688
- remove `query-string` module. (Not sure why we were using, since we get `querystring`
  from browserify.)

### CODE REVIEW

**Comment by ckprice** [comment]
Please don't merge this quite yet. We're having a GTM discussion tomorrow.

**Comment by lmorchard** [comment]
This is where #506 would really come in handy (i.e. django-waffle). Alternatively, this PR could tie disabling the query string gate to the value of the `ACCOUNT_INVITE_ONLY_MODE` flag as a feature flip.

In general, it's a really bad idea to hold PR code merges back until the last minute as a switching mechanism. We want to review and troubleshoot the code ASAP to surface issues - activating/deactivating features should be the function of a simple switch to decouple that from code review concerns. In this case, it shouldn't be a big deal, but I want to raise it for future issues.

**Comment by ckprice** [comment]
This is no longer blocked. We can merge once reviewed, then push with our Monday deployment.

**Comment by meandavejustice** [comment]
@ckprice lemme fix this with a rebase and we can merge

_updated_

**Comment by lmorchard** [comment]
Need to also remove the `isMoz` blocks from the landing-page template. The query string gate is gone, but that means there's no way to get past the "Something's Up" message since `isMoz` is always undefined (i.e. false).

```
➜  testpilot git:(meandavejustice-688-remove-querystring-gateway) ✗ find ./testpilot/frontend/static-src -type f -exec grep -Hni 'isMoz' {} \;
./testpilot/frontend/static-src/app/templates/landing-page.js:4:        {{^isMoz}}
./testpilot/frontend/static-src/app/templates/landing-page.js:24:        {{/isMoz}}
./testpilot/frontend/static-src/app/templates/landing-page.js:25:        {{#isMoz}}
./testpilot/frontend/static-src/app/templates/landing-page.js:120:      {{/isMoz}}
```

**Comment by meandavejustice** [comment]
@lmorchard Fixed, thank you.

**Comment by lmorchard** [comment]
Yup, looks good now!

**Pull request merged**
