### PR TITLE
[News Feed] Footer links are now displayed on left

### PR DESCRIPTION
**Pull request by divyabaid16**
Fix : #3341

### CODE REVIEW

**Comment by meandavejustice** [comment]
The unit tests are failing because of missing [flow-type](https://flow.org/en/docs/) definitions

```
frontend/src/app/components/FeaturedExperiment/index.js:50
 50:     const { experiment, enableExperiment } = this.props;
                             ^^^^^^^^^^^^^^^^ property `enableExperiment`. Property not found in
 50:     const { experiment, enableExperiment } = this.props;
                                                  ^^^^^^^^^^ object type
```

If you have trouble figuring out what needs to be added, ping one of us in the #testpilot irc

**Comment by divyabaid16** [comment]
@meandavejustice , as you said that The unit tests are failing because of missing flow-type definitions. So how come my PR [#3357](https://github.com/mozilla/testpilot/pull/3357) prior to this was merged? 
Moreover how do I add the flow type definitions?

**Comment by chuckharmston** [comment]
@divyabaid16 The flow type definitions that were causing the build to fail were unrelated to your code, no worries about that. We'll fix it in #3361 and ignore the failing build here for now.

I'll start reviewing momentarily!

**Comment by chuckharmston** [comment]
Works as advertised! Thanks for the contribution, @divyabaid16 👌

**Review by chuckharmston — APPROVED** [review]
Works as advertised! Thanks for the contribution, @divyabaid16 👌

**Pull request merged**
