### PR TITLE
L10n review notifications

### PR DESCRIPTION
**Pull request by lmorchard**
Two things going on here:

* Trying the new [CODEOWNERS feature](https://github.com/blog/2392-introducing-code-owners) to ping for review on string changes
* Adding some comments to the recently merged experiment platform strings, which hopefully should trigger the aforementioned ping

### CODE REVIEW

**Comment by lmorchard** [comment]
Hmm, doesn't look like it worked. Maybe CODEOWNERS needs to be merged before notifications automatically happen, which makes sense.

**Comment by lmorchard** [comment]
Weird thing, though is I can't add as a reviewer manually either...

**Comment by lmorchard** [comment]
Maybe had to add as a contributor first? Not sure if that means CODEOWNER pings will work in future PRs

**Comment by flodolo** [comment]
I think I already am listed as contributor (I see merge and close commands). It might make sense to merge the CODEOWNER part, and move the FTL test on a different PR

**Comment by lmorchard** [comment]
Revising to drop the app.ftl change

**Review by flodolo — APPROVED** [review]

**Pull request merged**
