### PR TITLE
Fix #2657 Remove ftl strings from old experiments so localizers don't have to translate strings which will never be shown anywhere.

### LINKED ISSUE #2657: [l10n] Remove content from old experiments
A contributor starting to localizing the website correctly noted that there's a ton of obsolete content in experiments.ftl

Example: AS, cliqz, nomore404, paheshot, etc.

Why can't we get rid of this content?

CC @rprys

### PR DESCRIPTION
**Pull request by fzzzy**
Once an experiment has graduated, the following strings should be
removed for the experiment:

- measurements
- prefeedbackcopy
- toursteps
- eolwarning

### CODE REVIEW

**Review by flodolo — APPROVED** [review]
Thanks for doing this! Do we need to add this information/guidelines somewhere?

**Review by lmorchard — CHANGES_REQUESTED** [review]
[You can't manually edit `experiments.ftl`, it's automatically generated from YAML.](https://github.com/mozilla/testpilot/blob/master/docs/content/reference.md#localization) The CircleCI failure reflects this, with a check to ensure that any strings extracted from YAML also appear in `experiments.ftl` as committed to git.

The only way to get these strings out of `experiments.ftl` is to remove them from YAML. That, or hack the extraction code to omit them.

**Comment by fzzzy** [comment]
@flodolo Yes, I think we should add it to any docs we have on graduating an experiment. (Do we have any? I'll look)

**Comment by fzzzy** [comment]
@lmorchard Oh, right. I always forget that :P Ok, I will remove them from the yaml.

**Review by lmorchard — APPROVED** [review]

**Comment by lmorchard** [comment]
Thought this would take me longer to look through, but seems like all the pages are working fine

**Pull request merged**
