### PR TITLE
fix header alignment on experiments

### PR DESCRIPTION
**Pull request by johngruen**

### CODE REVIEW

**Comment by johngruen** [comment]
Fixes #3720

**Comment by MozillaTestPilotStorybook** [comment]
# Storybook Deployment
Pull Request: http://testpilot-storybook.dev.mozaws.net/pull/3725/index.html
Commit: http://testpilot-storybook.dev.mozaws.net/2ff13eb2bdc2bed83177d5dbc0694531fd640181/

**Comment by vladikoff** [comment]
> Fixes #3725

Wrong number, which # does this fix?

**Comment by johngruen** [comment]
@vladikoff fixed

**Comment by devinreams** [comment]
Confirmed fixed in desktop and mobile browser sizes

screen shot 2018-07-10 at 6 24 26 am
screen shot 2018-07-10 at 6 24 30 am

**Review by devinreams — APPROVED** [review]

**Review by vladikoff — APPROVED** [review]

**Pull request merged**
