### PR TITLE
WIP: Added 3 new UI Integration tests

### PR DESCRIPTION
**Pull request by b4handjr**
Adding a few tests at a time. 

The three new tests are:
1. Checking that the Testpilot addon install button loads
2. Checks the number of experiments matches the ENV variable(would like some feedback on this one).
3. Checking to make sure that the page that loads when you click an experiment is correct.

@fzzzy @davehunt @krupa

### CODE REVIEW

**Comment by chuckharmston** [comment]
> Checks the number of experiments matches the ENV variable(would like some feedback on this one).

You may want to look at `/api/experiments.json`, which will contain an array of all the experiments for any given build. You'll need to compare with the `completed` and `launch_date` for each experiment to see if it should be active, but it's better than an environment variable.

**Comment by b4handjr** [comment]
> You may want to look at /api/experiments.json, which will contain an array of all the experiments for any given build. You'll need to compare with the completed and launch_date for each experiment to see if it should be active, but it's better than an environment variable.

Is that within this repo?

**Comment by chuckharmston** [comment]
> Is that within this repo?

No, it's built with `npm run content`.

**Comment by b4handjr** [comment]
@chuckharmston how does my implementation look?

**Review by fzzzy — CHANGES_REQUESTED** [review]
This looks good to me. Please squash it for merge.

**Comment by b4handjr** [comment]
@fzzzy should be good

**Review by fzzzy — APPROVED** [review]

**Pull request merged**
