### PR TITLE
added 'subtitle' to experiment yaml

### LINKED ISSUE #1138: Add optional subtitles the right way
This is a follow on to #1137 

Once we get through this train, we should implement an optional subtitle for each experiment that cleans up the experiment-specific logic of #1137

### PR DESCRIPTION
**Pull request by dannycoates**
fixes #1138

### CODE REVIEW

**Review by lmorchard — APPROVED** [review]
:+1:

**Comment by johngruen** [comment]
man, that was fast

**Comment by pdehaan** [comment]
Do we need/want to add the new `subtitle` field to the [experiment YAML template](https://github.com/mozilla/testpilot/blob/master/docs/experiments/experiment-content/template.yaml)?

**Comment by johngruen** [comment]
Yeah, i can do a follow on here

**Pull request merged**
