### PR TITLE
add new notes contributors

### PR DESCRIPTION
**Pull request by vladikoff**
@johngruen r?

### CODE REVIEW

**Review by chuckharmston — CHANGES_REQUESTED** [review]
@vladikoff since you're changing strings, you'll need to update the English locale file. That's why the build is failing. More here:

https://github.com/mozilla/testpilot/blob/master/docs/content/reference.md#localization

Moving Udara down in the list in particular my have some deleterious effects to localization. I'd suggest not doing that.

**Comment by vladikoff** [comment]
@chuckharmston by new strings do you mean titles such as `title: 'Community Contributor'`?

**Comment by chuckharmston** [comment]
Indeed. Those need to be localized.

**Comment by vladikoff** [comment]
@chuckharmston ok I removed the new "cool" titles and moved Udara back, so no new strings just new people :)

**Comment by chuckharmston** [comment]
Unfortunately, that won't do it; even though the content of the strings may not be new, the string itself is. Sébastien's and Ethan's titles, for example, are considered different strings in the system.. 

[Activity Stream's](https://github.com/mozilla/testpilot/blob/master/locales/en-US/experiments.ftl#L6-L18) contributor titles might be a nice example (note that #7 and #8 are the same text). 

The documentation I linked in the original review explains the process of generating a new locale file well.

**Comment by SoftVision-PaulOiegas** [comment]
@vladikoff Since we are modifying this section, would you guys mind to add Marius Coman too? He's doing a lot of QA on Notes side by side with Emil and he has the same "title" as him.
Would be much appreciated, but no hard feelings if you guys don't consider it ok. :)

**Comment by vladikoff** [comment]
@SoftVision-PaulOiegas for sure! 👍

**Comment by SoftVision-PaulOiegas** [comment]
@vladikoff Thanks a lot!I bet he will be quite happy to see his name there.

**Comment by chuckharmston** [comment]
@vladikoff With this most recent commit, by changing the indexes of contributors (e.g. @rfeeley changes from notesContributors2 to notesContributors5) you're changing the meaning of some strings without invalidating existing translations using `_l10nsuffix`. You'll either need to invalidate all the affected titles (not preferred, because we don't want to waste localizers' time) or just add the new contributors to the bottom of list.

**Comment by vladikoff** [comment]
> just add the new contributors to the bottom of list.

Okay :(

**Review by chuckharmston — APPROVED** [review]

**Comment by chuckharmston** [comment]
@flodolo r?

**Review by flodolo — APPROVED** [review]

**Comment by vladikoff** [comment]
Thank you all!! 🍰

**Pull request merged**
