### PR TITLE
style button icon with css instead of js

### PR DESCRIPTION
**Pull request by dannycoates**
Follow-up to #1203 

Remove all the js hackery in favor of smooth css

### CODE REVIEW

**Comment by lmorchard** [comment]
Works for me!

**Comment by bwinton** [comment]
So, there's a small problem with the CSS when the browser window doesn't have focus…
screen shot 2016-08-05 at 18 39 24
Maybe we can make the selector a little more restrictive in a followup PR?

(Found by @phlsa, reported via Slack.)

**Comment by lmorchard** [comment]
Yeah, let's file a new issue for that. This PR is already merged

**Comment by SoftVision-PaulOiegas** [comment]
Yep we found it too in #1215 . But it's only visible for a few minutes after installation.

**Pull request merged**
