### PR TITLE
close settings menu on body click

### LINKED ISSUE #292: Settings popup is too sticky
Not a huge problem on the [home page](http://idea-town-dev.elasticbeanstalk.com/home)[1] where we have a header, but the settings popup is a mildly annoying on the [details page](http://idea-town-dev.elasticbeanstalk.com/experiments/test-title) where it obscures the Enable[2] and Disable[3] buttons.

Not sure if we can close the popup when the user does a `mouseout` or something similar.

idea_town
[1] Home page w/ header.

---

idea_town
[2] Enable experiment

---

idea_town
[3] Disable experiment

### PR DESCRIPTION
**Pull request by meandavejustice**
fix #292

### CODE REVIEW

**Comment by johngruen** [comment]
@pdehaan also, totally unrelated to this specific PR, but travis seems to be going crazy slow lately

**Comment by pdehaan** [comment]
@johngruen I think "running for 2 hrs 58 min 9 sec" counts as crazy slow.

**Comment by meandavejustice** [comment]
what the hell travis `running for 15 hrs 9 min 38 sec`

**Comment by johngruen** [comment]
LGTM! Thanks for making those tweaks @meandavejustice.

@pdehaan what say ye?

**Comment by pdehaan** [comment]
@johngruen If you're happy, I'm happy. Let's merge it now and we can tweak later if needed.

**Pull request merged**
