### PR TITLE
add some tweaks to the more experiments arrow

### LINKED ISSUE #3333: [Enhancement] The "More Experiments" button and animation should be placed differently on mobile view
**[Affected versions]:**
- Firefox 58.0.1 (mobile)

**[Affected Platforms]:**
- Android 7.0 (Samsung Galaxy S6)
- Android 8.0 One Plus 5

**[Prerequisites]:**
- Latest Firefox browser version was installed on the mobile device.

**[Steps to reproduce]:**
1. Start the Firefox Android app and navigate to https://testpilot.firefox.com page.
2. Observe how the "More Experiments" button with animated arrow are displayed in portrait mode.

**[Expected result]:**
- The button with animation and text are displayed on the page in such a way that they don't obstruct any page elements and the button text it's readable.

**[Actual result]:**
- The button with animation and text is overlapping the page elements in mobile view, making both of them to be almost unreadable

**[Notes]:**
- A possible suggestion would be to move the button on the right side of the page where it obstructs less page elements, especially the top part of the page.
- Here are some screenshots of the issue:

screenshot_20180207-125251

### PR DESCRIPTION
**Pull request by johngruen**
Fixes #3333 for @SoftVision-PaulOiegas but also removes pointer events from the `.more-button` div that blocked clicks on the install button

### CODE REVIEW

**Comment by johngruen** [comment]
also, svgos the two svgs i didn't see in #3358

**Comment by MozillaTestPilotStorybook** [comment]
# Storybook Deployment
Pull Request: http://testpilot-storybook.dev.mozaws.net/pull/3359/index.html
Commit: http://testpilot-storybook.dev.mozaws.net/12fae5e448e85ba6261f483198a24bd4042eb331/

**Comment by meandavejustice** [comment]
Looks like the "More Experiments" button is floating to the right now with this update

#### Production
(arrow centered)
prod-mobile-more-experiments

#### Local (pr/3359)
(arrow floating right)
3333-arrow-local

**Review by meandavejustice — CHANGES_REQUESTED** [review]
More Experiments button appears to be floating right now in responsive design mode mobile views.

**Comment by johngruen** [comment]
@meandavejustice that was by design :)

**Pull request merged**
