### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by lcapalbo**

### CODE REVIEW

**Comment by flodolo** [comment]
cc @avelper 
Thanks Lucas, this seems easy enough to take even for a non Spanish speaker.

Note that translation happens in a tool. Unfortunately, attribution won't get imported from GitHub (but it will show up in the history here)
https://pontoon.mozilla.org/es-ES/

If you want to contribute to localization, feel free to get in touch with the existing team
https://pontoon.mozilla.org/es-ES/info/

**Comment by avelper** [comment]
Hi!

Sorry, but I am a bit lost here... I don't find where the typo is. Anyone can help so I can update it?

Thanks!

**Comment by flodolo** [comment]
Ugh, I completely forgot that localization is in the l10n branch now :-\

For that reason, the typo was still in Pontoon
https://pontoon.mozilla.org/es-ES/test-pilot-website/app.ftl/?search=oneClickInstallMinorCta&string=162055

I've fixed it manually

**Comment by avelper** [comment]
Great, thanks a lot!

**Comment by SoftVision-PaulOiegas** [comment]
@flodolo This was only fixed for the Test Pilot "Homepage". The "Experiment details" page still has the typo (see #2906).

**Pull request merged**
