### PR TITLE
Fix flow and show email dialog unit tests

### PR DESCRIPTION
**Pull request by meandavejustice**

### CODE REVIEW

**Comment by b4handjr** [comment]
For the failures the tests currently look for a popup to appear. As it seems those don't appear every time now, it would be okay to wait for the notification that confirms the extension has been installed to be closed. If you were to remove the line checking for the popup to be shown, that should work.

**Comment by b4handjr** [comment]
Add this to your ```conftest.py```: ```firefox_options.set_preference('ui.popup.disable_autohide', True)```

**Comment by SoftVision-PaulOiegas** [comment]
@jrbenny35 I think what you are mentioning is hitting #3142.

**Comment by meandavejustice** [comment]
@jrbenny35 I've made some progress with this, but I think I've hit a wall. Would you mind taking a look? hacked on it on and off all weekend and still can't all of them to pass

**Comment by chuckharmston** [comment]
@meandavejustice it looks like you at least have the Flow fixes [working well](https://circleci.com/gh/mozilla/testpilot/8132?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link). Any chance you could factor that into a separate PR?

**Pull request merged**
