### PR TITLE
Fix #1828 Tell fluent not to emit FSI and PDI characters.

### LINKED ISSUE #1828: Edge Browser Making Extra Boxes around some template strings
screen shot 2016-11-17 at 2 39 37 pm

Just noticed this while debugging edge's SVG behavior.

### PR DESCRIPTION
**Pull request by fzzzy**

### CODE REVIEW

**Comment by fzzzy** [comment]
I don't actually have a windows box conveniently set up to test this right now, can someone with Edge try this out? Thanks.

**Comment by SoftVision-PaulOiegas** [comment]
Hi @fzzzy I've tried to test this locally but recently `npm start` gives a lot of errors on Windows 10. It correctly works on Mac OS, so something broke in the last days on Windows since last week I could test locally without any issues on my Windows machine.

Here is a [screenshot with the errors](https://drive.google.com/open?id=19qp4nlO_sXIvndtCQDXK0MqFz-k_cxkV), if you can fix them, I will help you to test this. 

I also tried to share my iMac connection and connect my windows machine trough it, but t's a bit complicated and time consuming to make right now.

**Comment by fzzzy** [comment]
@SoftVision-PaulOiegas We talked about it a bit, and the problem may be that your node version on windows is too old. Make sure you have 8.9.4. Thanks!

**Comment by SoftVision-PaulOiegas** [comment]
I've upgraded Node to 8.9.4 and npm to 5.6.0 and I still get errors when trying to `npm start`... So I'm not really sure that this is on my end, since a few days ago was perfectly working.

I'll try again the setup from scratch, maybe also on a different machine and I will let you know.

**Comment by SoftVision-PaulOiegas** [comment]
I managed to start it after all. Probably due to old node and npm versions the cloned repo was somehow corrupted to. After a clean setup I managed to start the webserver properly and verify the fix. Seems ok to me, haven't found any of those FSI and PDI characters on experiment details pages.

I think this is good to be merged. 👍

**Pull request merged**
