### PR TITLE
fix #2880: containers graduation

### LINKED ISSUE #2880: Graduate Containers from Test Pilot to AMO
* [x] Move the add-on and users to AMO
* [x] Write graduation post on Medium
* [ ] Update the testpilot.firefox.com page for Containers (Should I just send a PR to the containers.yml file?)

### PR DESCRIPTION
**Pull request by groovecoder**

### CODE REVIEW

**Comment by johngruen** [comment]
Boop

**Comment by MozillaTestPilotStorybook** [comment]
# Storybook Deployment
Pull Request: http://testpilot-storybook.dev.mozaws.net/pull/2923/index.html
Commit: http://testpilot-storybook.dev.mozaws.net/d6e80018274e196a98bfcaade4da5481f28d9ae6/

**Comment by groovecoder** [comment]
This should go live today, yes?

**Comment by fzzzy** [comment]
@groovecoder Our release has slipped until at least tomorrow.

**Pull request merged**
