### PR TITLE
Remove HTML from tour steps.

### PR DESCRIPTION
**Pull request by chuckharmston**

### CODE REVIEW

**Comment by lmorchard** [comment]
Is there an associated issue with some background? At one point, we explicitly wanted HTML in these tour steps - e.g. in case we wanted to link out to more info on some feature or another. Don't want to take out the capability if we still want to use it some day.

Might also want to let the initial wave of localization work to die down unless this is an urgent change.

**Comment by chuckharmston** [comment]
It was [requested](https://github.com/mozilla/testpilot/issues/1778#issuecomment-259136231) by @mathjazz and @flodolo of the localization team. HTML makes localization really challenging, as changes to structure are tightly coupled to the localizations. We could still have the ability to link out if that becomes a need—we'd just need to re-add `dangerouslySetInnerHtml` to the appropriate spot.

**Comment by jaredhirsch** [comment]
I see a _lot_ of other strings that still have html in them. Is there any reason not to fix those strings at the same time?

**Comment by chuckharmston** [comment]
@6a68 I'm doing just that (see #1768), just trying to keep PRs small to make them more reviewable.

**Comment by lmorchard** [comment]
Yeah, would rather get these in a big single batch and wait until after Pontoon activity dies down. Would also like to be sure we don't want HTML in those fields, because it seems harder to add it back in once we have localizations.

**Comment by chuckharmston** [comment]
I guess that's fine, but:

1) We need to make sure we don't invalidate localizers' hard work, and the longer we wait, the harder this will be.
2) Dibs on not massaging all the files by hand.

**Comment by jaredhirsch** [comment]
HTML in l10n strings is a bummer for multiple reasons. Biggest one is, if localizers typo the tags, that stuff gets checked in without a review--so QA has to check that, eg., links aren't broken, for every locale. That's a lot of needless work.

Another thing is, changing the HTML structure suddenly depends on an army of volunteers.

If we instead assemble the HTML ourselves, like "grab this key and that key and shove into this template string", life is easier.

**Comment by chuckharmston** [comment]
> it seems harder to add it back in once we have localizations.

It's really not; we aren't giving up any capability here, just adding more structure and making localization easier.

If we want to add links to tour steps, You just need to change this line:

``` jsx
<p data-l10n-id={this.l10nId(['tour_steps', idx, 'copy'])}>{step.copy}</p>
```

to this:

``` jsx
<p data-l10n-id={this.l10nId(['tour_steps', idx, 'copy'])} dangerouslySetInnerHTML={createMarkup(step.copy)}></p>
```

I'm doing that here: https://github.com/mozilla/testpilot/pull/1786

**Comment by jaredhirsch** [comment]
Closing, blocked on #1811 for now. See [my comment in other PR](https://github.com/mozilla/testpilot/pull/1786#issuecomment-263340519) for discussion.

**Pull request closed without merging**
