### PR TITLE
fix miscolored button on win-10 addon

### LINKED ISSUE #2007: Button label in feedback bar has wrong color on Windows
The button label for taking a survey is really hard to read on Windows (10). I assume that either the label should have been black or that the button color should have been blue.
snip_20170110151452

### PR DESCRIPTION
**Pull request by johngruen**
Fixes #2007 

Uses an inset box-shadow to git around windows weird dislike of colored XUL buttons

### CODE REVIEW

**Comment by johngruen** [comment]
screen shot 2017-01-17 at 10 08 42 am

**Comment by chuckharmston** [comment]
I don't think it's a winning battle to try to fight native platform styles for these things; for #1770 @sevaan and I just abandoned the button CSS entirely. Probably worth considering here.

**Comment by johngruen** [comment]
meh, technique works, button stands out more...I'm not sure i understand the downside when the Default botton style is far less eye-catching

**Comment by jaredhirsch** [comment]
Looks like this PR has gone stale. I'm inclined to just merge this and see what happens, so, here we go

**Pull request merged**
