### PR TITLE
Add Noitidart to min vid contributors

### LINKED ISSUE #1842: Add Noitidart to contributors on experiment page
refs 
https://github.com/meandavejustice/min-vid/issues/479

### PR DESCRIPTION
**Pull request by meandavejustice**
- fixes #1842 
noitidart-contributor

### CODE REVIEW

**Comment by Noitidart** [comment]
Too cool, thank you!

**Review by chuckharmston — CHANGES_REQUESTED** [review]
Can you resize the avatar to 64x64 please?

https://github.com/mozilla/testpilot/blob/master/docs/content/reference.md#contributors

**Comment by Noitidart** [comment]
Hi @chuckharmston sure thing - here it is - http://i.imgur.com/qovXAES.png

**Comment by meandavejustice** [comment]
@chuckharmston updated

**Review by chuckharmston — APPROVED** [review]

**Pull request merged**
