### PR TITLE
Updated individual html reports

### PR DESCRIPTION
**Pull request by b4handjr**
Adds individual reporting to try and fix the current failures.

### CODE REVIEW

**Comment by lmorchard** [comment]
Watching the CircleCI run with bated breath

**Comment by lmorchard** [comment]
Hmm :( `frontend/test/ui/test_homepage.py::test_copter_loads ERROR`

**Comment by b4handjr** [comment]
Ugh, let me remove the html reporting. It seems to be messing with the error

**Comment by lmorchard** [comment]
🎆 :100: 🎆

**Pull request merged**
