### PR TITLE
add dev flag; fixes 1690

### PR DESCRIPTION
**Pull request by clouserw**
/cc @relud -- can you confirm our dev environment has this flag on it now so we can deploy this without hiccuping?  Thanks.

### CODE REVIEW

**Comment by relud** [comment]
I don't own the testpilot dev environment. I think @lmorchard does.

**Comment by lmorchard** [comment]
Yeah, dev is owned by devs on Cloud Services AWS - hopefully not just me, bus factor and all that. It's deployed via circle.yml and [`deploy.sh` gets run here](https://github.com/mozilla/testpilot/blob/master/circle.yml#L44). Should able to add the `dev` param there

**Review by lmorchard — CHANGES_REQUESTED** [review]
Realized my last comment wasn't a change request - you should be able to wrap this up with adding the `dev` param to [the deploy.sh call in circle.yml](https://github.com/mozilla/testpilot/blob/master/circle.yml#L44)

**Comment by ghost** [comment]
Thanks @lmorchard . new patch is pushed

**Review by chuckharmston — APPROVED** [review]

**Pull request merged**
