### PR TITLE
Fix privacy notice checkbox error in newletter form not showing

### LINKED ISSUE #3042: [Newsletter] Notification that informs about the need to check the privacy notice checkbox is no longer displayed
**[Affected versions]:**
- Firefox 56.0.2 and above

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Prerequisites]:**
- Following 5 prefs have been set or added on a new profile: "extensions.legacy.enabled = true" "xpinstall.signatures.required = false" "testpilot.env = dev" "extensions.webapi.testing = true" "extensions.install.requireBuiltInCerts = false".

**[Steps to reproduce]:**
1. Open Firefox browser and navigate to https://testpilot.dev.mozaws.net page.
2. Click the "Install the Test Pilot Add-on" big green button.
3. After TxP "Newsletter sign up" dialog is displayed, click the text field in order to focus it.
4. Enter a valid email address and leave the privacy checkbox unchecked.
5. Click the "Sign Up Now" button and observe the dialog behavior. 

**[Expected result]:**
- The sign up process is not performed and you are notified that you need to check the privacy notice checkbox in order to proceed.

**[Actual result]:**
- No notification is displayed that informs you about the need to check the privacy notice checkbox.

**[Notes]:**
- The same behavior occurs also for the footer Newsletter sign up form.
- Here is a screen recording of the behavior https://goo.gl/9Ussyv.

### PR DESCRIPTION
**Pull request by meandavejustice**
- fixes #3042

form-error

### CODE REVIEW

**Comment by SoftVision-PaulOiegas** [comment]
Shouldn't that error point to the checkbox? 😄 Was doing that before it disappeared.

**Comment by meandavejustice** [comment]
@SoftVision-PaulOiegas I was going off of this, https://github.com/mozilla/testpilot/issues/3042#issuecomment-356171913, but I think you are right, it should point to the checkbox

**Comment by meandavejustice** [comment]
updated position 
checkbox-error-position

**Comment by chuckharmston** [comment]
Meta question: why are we using custom interface elements for things that the browser has defaults for? I think we should be using `required="required"` on the form element instead.

**Comment by meandavejustice** [comment]
@chuckharmston I agree, @fzzzy also brought this up. Sounds like that would be a good issue for us to file with the `dev-papercut` label. Might also become a `good-first-issue`

**Review by chuckharmston — CHANGES_REQUESTED** [review]
I'm not sure we should be adding code + complexity that we know can be done better, simpler. Can you refactor to use HTML form validation instead?

**Comment by meandavejustice** [comment]
@chuckharmston ~~I'm happy to refactor but I'm not sure it makes sense for this issue. We aren't really adding any code in this issue, it's tweaking to fix the existing implementation. I would rather get this merged, as its a minor tweak that gets our signups working, and get the required field version in at a later date.~~

On second thought, it's not too big of a change to switch to the required fields. I'll just make the changes :)

**Comment by fzzzy** [comment]
I know this code previously used required="required". Not sure when it changed.

**Comment by meandavejustice** [comment]
@fzzzy I'll look through history and see if I can just do what we were doing before

**Comment by chuckharmston** [comment]
@meandavejustice is this ready for re-review?

@flodolo looks like we need your review here as well; we're removing a string and are replacing it with native browser validation.

**Comment by meandavejustice** [comment]
@chuckharmston indeed, it is ready for review

**Review by flodolo — APPROVED** [review]
In case I don't reply quickly, feel free to go ahead when you're only removing strings ;-)

**Comment by flodolo** [comment]
This is also going to conflict, one way or the other, with #3349. Not sure if Git will be smart enough.

**Comment by chuckharmston** [comment]
screen shot 2018-02-15 at 10 29 02

**Review by chuckharmston — APPROVED** [review]
Works great, looks great, and I love deleting code. Thanks for sticking with it!

**Pull request merged**
