### PR TITLE
Fix #2102 Require safari users agree to the privacy terms.

### LINKED ISSUE #2102: Newsletter signup is wrongly performed without checking the privacy agreement checkbox on Safari browser
[Affected versions]:
- Safari v10.0

[Affected Platforms]:
- All Mac OS

[Steps to reproduce]:
1. Open Safari browser and navigate to "https://testpilot.stage.mozaws.net.com" page.
2. Scroll the page until Newsletter section is reached.
3. Enter a valid email address.
4. Leave the checkbox unchecked and click on "Sign Up Now" button.
5. Observe page behavior.

[Expected result]:
- You are prompted to check the agreement checkbox if you want to continue.

[Actual result]:
- The subscribe is wrongly performed and the "Thanks" message is displayed.

[Notes]:
- The subscription email is sent and email is subscribed.
- This reproduces on all servers, including production.
- This does not reproduces on Firefox (Mac OS & Win), Chrome (Mac OS & Win), Edge (Win) or Opera (Win) browsers.

### PR DESCRIPTION
**Pull request by fzzzy**

### CODE REVIEW

**Comment by jaredhirsch** [comment]
Looking now

**Comment by jaredhirsch** [comment]
Here's how this looks on Safari:

screen shot 2017-03-02 at 12 46 20 pm

**Review by jaredhirsch — CHANGES_REQUESTED** [review]
Nice work. Looks good overall.

Could you add some space between the end of the error message and the regular string? See the screenshot I posted in a separate comment. 

I'm good to merge once that change is made.

**Comment by fzzzy** [comment]
@6a68 Sure. I already tried to make that change and failed, but I will try again.

**Comment by fzzzy** [comment]
I fixed the whitespace thing.

**Pull request merged**
