### PR TITLE
[fix #1042] Update PN & TOS for removal of FxA

### LINKED ISSUE #1042: Update privacy policy & terms of use reflecting FxA removal
Needs details / a conversation with legal?

### PR DESCRIPTION
**Pull request by ckprice**
**DO NOT MERGE** yet please. I'd like legal to sign off on this.

The date is currently set to July 19 in the documents. This needs to correspond to when the FxA changes land.

Fixes #1042.

### CODE REVIEW

**Comment by ckprice** [comment]
This has been approved by legal, but keeping the DO NOT MERGE status on until we're sure that TXP-7 will ship in the next deployment.

**Comment by johngruen** [comment]
@eleemoz says 👍, Let's merge this when the last of TxP-7 is in place

**Comment by lmorchard** [comment]
If the date is the only thing we're waiting on, we could merge this now to get it in and then tweak the date just before deployment. Ideally we won't need to change it though

**Comment by ghost** [comment]
This is all looking good.  Merging...

**Pull request merged**
