### PR TITLE
Add blog link

### PR DESCRIPTION
**Pull request by johngruen**
Fixes #2121

### CODE REVIEW

**Review by flodolo — APPROVED** [review]
No issue for l01n (for clarity, I only look at strings in the FTL, not at the code)

**Comment by flodolo** [comment]
> No issue for l01n (for clarity, I only look at strings in the FTL, not at the code)

I wonder if I should avoid reviewing the strings explicitly, since they make the PR reviewed and it might be confusing.

**Review by lmorchard — APPROVED** [review]
:+1: - with one nit: Would like to see the two commits squashed and a "Fixes #2421" added to the comment

**Comment by lmorchard** [comment]
> I wonder if I should avoid reviewing the strings explicitly, since they make the PR reviewed and it might be confusing.

I think it's fine... just having a single approval doesn't mean a PR shouldn't have more

**Comment by johngruen** [comment]
Squashed...will merge when tests finish

**Comment by SoftVision-PaulOiegas** [comment]
@johngruen If I understood well from the PR code, the blog link should be displayed only on top of the page, right? You haven't mentioned any details about it. 
Adding an "M" button on the footer beside GitHub and Twitter ones would be to much?

**Pull request merged**
