### PR TITLE
RESTART_NEEDED code removed

### PR DESCRIPTION
**Pull request by rsenwar**
All unnecessary code removed.

### CODE REVIEW

**Comment by rsenwar** [comment]
@chuckharmston Please have a look at this.

**Review by chuckharmston — CHANGES_REQUESTED** [review]
This is an excellent start, thanks @rsenwar!

Quite a bit more work to be done here, such as the [`RestartPage`](https://github.com/mozilla/testpilot/blob/93c9ea7aa6104fbbdc21508e44d486d7ca7c77aa/frontend/src/app/containers/RestartPage.js) component being removed, as well as the [`requireRestart`](https://github.com/mozilla/testpilot/search?utf8=%E2%9C%93&q=requireRestart&type=) prop that is passed around the app.

[This search](https://github.com/mozilla/testpilot/search?l=JavaScript&q=restart&type=&utf8=%E2%9C%93) should be a good start. Additionally, the [`restartIntro` section of the English string file](https://github.com/mozilla/testpilot/blob/17c86e7b049c78b8cbebdfef1fa46801d99183f4/locales/en-US/app.ftl#L194-L199) should be removed (the other locale files will be updated automatically afterward).

**Review by rsenwar — COMMENTED** [review]
restartIntro section removed

**Comment by meandavejustice** [comment]
@rsenwar Looks like there is a conflict, do you mind doing a rebase and we can try and get this merged. Thanks!

**Comment by dannycoates** [comment]
This got completed in #3458

**Pull request closed without merging**
