### PR TITLE
DO NOT MERGE only ship lockbox EN

### PR DESCRIPTION
**Pull request by johngruen**

### CODE REVIEW

**Comment by johngruen** [comment]
@devinreams if you want Lockbox to ONLY APPEAR on EN versions of the Test Pilot site, we have to merge this patch and push it to stage and prod with our release today!

**Comment by johngruen** [comment]
@devinreams we could further restrict by making this en-US instead of en

**Comment by MozillaTestPilotStorybook** [comment]
# Storybook Deployment
Pull Request: http://testpilot-storybook.dev.mozaws.net/pull/3724/index.html
Commit: http://testpilot-storybook.dev.mozaws.net/d5c4381d34af8c1b552e8f8d8b8e2d16333867db/

**Comment by devinreams** [comment]
I _think_ we want to consider where we see interest (from other regions/languages) for product prioritization purposes.

Holding off on a final decision on if/when to merge this pending further discussion with @johngruen @sandysage

**Comment by meandavejustice** [comment]
@johngruen Can we close this?

**Pull request closed without merging**
