### PR TITLE
Update styles to match share modal mockup, modify step-modal min-height

### LINKED ISSUE #3122: The "Share" page modal does not follow the design
**[Affected versions]:**
- Firefox 57.0.1 and above

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Prerequisites]:**
- Following 5 prefs have been set or added on a new profile: "extensions.legacy.enabled = true" "xpinstall.signatures.required = false" "testpilot.env = dev" "extensions.webapi.testing = true" "extensions.install.requireBuiltInCerts = false".

**[Steps to reproduce]:**
1. Open Firefox browser and navigate to https://testpilot.dev.mozaws.net/share page.
2. Observe the "Share" page modal.

**[Expected result]:**
- The "Share" page modal is looking and working as designed.

**[Actual result]:**
- The "Share" modal has lots of differences from the design (see attached screenshot).

**[Notes]:**
- See attached screenshot:
share differences

### LINKED ISSUE #3124: The experiments tour modal content is wrongly loading in two steps
**[Affected versions]:**
- Firefox 57.0.1 and above

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Prerequisites]:**
- Following 5 prefs have been set or added on a new profile: "extensions.legacy.enabled = true" "xpinstall.signatures.required = false" "testpilot.env = dev" "extensions.webapi.testing = true" "extensions.install.requireBuiltInCerts = false".

**[Steps to reproduce]:**
1. Open Firefox browser and navigate to https://testpilot.dev.mozaws.net page.
2. Scroll down and click on any active experiments cards (except Send).
3. Click the "Launch Tour" button on left column under "Experiment start date".
4. Observe how the modal content loads.
5. Click on the "Next" arrow and observe again how the modal content loads.

**[Expected result]:**
- The experiment "Tour" modal content is correctly loading without any delays.

**[Actual result]:**
- The experiment "Tour" modal content is loading in two steps, first the written content and after the image which also enlarges the modal.

**[Notes]:**
- This behavior only occurs at first load for each slide of the modal.
- See attached screen recording: https://goo.gl/9z77pr.

### PR DESCRIPTION
**Pull request by meandavejustice**
- fixes #3122
- fixes #3124

### CODE REVIEW

**Comment by MozillaTestPilotStorybook** [comment]
# Storybook Deployment
Pull Request: http://testpilot-storybook.dev.mozaws.net/pull/3125/index.html
Commit: http://testpilot-storybook.dev.mozaws.net/6171dd4156585571548e14114928e9ac829065cd/

**Comment by MozillaTestPilotStorybook** [comment]
# Storybook Deployment
Pull Request: http://testpilot-storybook.dev.mozaws.net/pull/3125/index.html
Commit: http://testpilot-storybook.dev.mozaws.net/0897a99bc38b2dc5fbd65b300dc05dd9b25f150c/

**Comment by MozillaTestPilotStorybook** [comment]
# Storybook Deployment
Pull Request: http://testpilot-storybook.dev.mozaws.net/pull/3125/index.html
Commit: http://testpilot-storybook.dev.mozaws.net/f9d0420dcf0b3352fcbd1a04265b14a0e44926af/

**Comment by fzzzy** [comment]
~~I'm still seeing sharp corners on the top of all the modals.~~

The share page modal has rounded corners, which is all we are concerned about here; the other sharp corners have other bugs covering them.

**Comment by fzzzy** [comment]
~~Can you add a 404 story while you are at it?~~

Never mind, that's not supposed to be a part of this pr

**Pull request merged**
