### PR TITLE
for #986: change "Leave" to "Uninstall"

### PR DESCRIPTION
**Pull request by groovecoder**
Now that I got my local environment running, I'm trying to make a simple contribution. I'm not sure if there's an automated extraction script to update the l20n strings? Or do I just change them manually to match?

### CODE REVIEW

**Comment by pdehaan** [comment]
@groovecoder Thanks for the contribution! Unfortunately, we don't have an auto-extraction script for l20n [yet], so you'll also need to manually tweak some strings in [/locales/en-US/app.l20n](https://github.com/mozilla/testpilot/blob/master/locales/en-US/app.l20n).

**Comment by groovecoder** [comment]
Updated the l20n strings too.

**Comment by groovecoder** [comment]
Think I got all the instances ...

testpilot-uninstall-menu

testpilot-uninstall-modal

testpilot-uninstall-terms

**Comment by meandavejustice** [comment]
Thanks!

**Pull request merged**
