### PR TITLE
Switch to Telemetry data for experiment usage counts

### PR DESCRIPTION
**Pull request by lmorchard**
Issue #1039

### CODE REVIEW

**Comment by lmorchard** [comment]
Whoops. Some clean up needed to clear linting errors... done

**Comment by lmorchard** [comment]
Hmm, maybe there's more broken than I thought. Will check out again on monday

**Comment by lmorchard** [comment]
Backing out the add-on cleanup to see if things will pass with just this simple telemetry URL change.

**Review by dannycoates — APPROVED** [review]
Works for me!

**Pull request merged**
