### PR TITLE
'Completed Experiment' addon changes

### PR DESCRIPTION
**Pull request by dannycoates**
This is a pretty hacktastic implementation of #1303

I made this survey a bit more persistent than the other ones. Since it pops up on a new tab it's got some `persistence` so it stays visible after navigating and it doesn't mark the survey as "done" if it times out and dismisses itself so that the panel will continue to link to the survey.

Tests?  `¯\_(ツ)_/¯`

### CODE REVIEW

**Comment by dannycoates** [comment]
screen shot 2016-09-07 at 9 52 40 am

The survey prompt diverges from the design slightly. I kept the stars from the other surveys instead of the 'Give Feedback' button.

**Comment by dannycoates** [comment]
FWIW this PR could be merged in a different sprint from #1301 and #1302 without breaking anything.

**Comment by dannycoates** [comment]
#1353 clobbers the survey changes here. Since that PR seems more important I'll rebase this against it once its merged.

**Comment by lmorchard** [comment]
Looks like #1353 was merged - does this still need a rebase? I see commits after that comment, but github is confusing me with the "added some commits 16 days ago" thing. So, could be already rebased

**Comment by lmorchard** [comment]
Could use some tests, yeah. Otherwise, looks fine & works

**Comment by dannycoates** [comment]
> does this still need a rebase?

Its up to date now

**Review by lmorchard — APPROVED** [review]
Looks good, let's merge

**Pull request merged**
