### PR TITLE
simplify onboarding ui

### LINKED ISSUE #1197: Simplify experiment onboading tour
This was feedback from @ckarlof:

He installed an experiment and saw this page:
tour

And thought we could eliminate a click if we just dropped right into the tour.  If a person wants to skip it, they can skip it from step 1 instead of step 0.

### PR DESCRIPTION
**Pull request by johngruen**
Fixes #1197

### CODE REVIEW

**Comment by johngruen** [comment]
I made some minor alterations to @sevaan's flow b/c the height of the new UI was somewhat problematic:

screen shot 2016-09-18 at 3 57 49 pm
screen shot 2016-09-18 at 3 57 43 pm

**Comment by sevaan** [comment]
Looks good @johngruen

On Sun, Sep 18, 2016 at 3:58 PM John Gruen

<
mailto:John Gruen notifications@github.com

> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

I made some minor alterations to
https://github.com/sevaan
's flow b/c the height of the new UI was somewhat problematic:

https://cloud.githubusercontent.com/assets/3323249/18618626/af5c4f18-7db8-11e6-8abe-42e467064fcd.png https://cloud.githubusercontent.com/assets/3323249/18618627/af5f3322-7db8-11e6-9ecb-b53d62801b47.png

—

You are receiving this because you were mentioned.

Reply to this email directly,
https://github.com/mozilla/testpilot/pull/1377#issuecomment-247871693
, or

**Comment by johngruen** [comment]
@sevaan 
giphy

**Comment by chuckharmston** [comment]
Real talk: why did contestants struggle so much with The Shrink of the Silver Monkey? It was a three-piece puzzle. It's not that complicated.

wg5oeq

**Comment by johngruen** [comment]
I blame Olmec

**Comment by chuckharmston** [comment]
I'm going to name my next pet Olmec.

**Review by lmorchard — APPROVED** [review]
Looks good to me & works

**Comment by lmorchard** [comment]
@johngruen - The new repo settings we enabled this morning make things more strict, and I can't merge without an update to the branch. But, I think you can update the branch with the button up there and merge yourself now that I submitted an r+ review.

**Comment by johngruen** [comment]
@lmorchard roger

**Pull request merged**
