### PR TITLE
add an about page

### PR DESCRIPTION
**Pull request by johngruen**
@clouserw the copy here will need to get reviewed before tuesday, so we may need to get a supplemental PR for this, but i'd like to get it reviewed and in today.

### CODE REVIEW

**Comment by johngruen** [comment]
Fixes #1249 and (for fun) #973

**Comment by lmorchard** [comment]
I can take a quick look, with regard to the page generation

**Comment by johngruen** [comment]
@lmorchard thanks! To clarify, our copy editor is looking at the text in the about.md page, but it's open season on everything else.

**Review by lmorchard — APPROVED** [review]
So, :+1: for the changes to generated pages, and the about page gets built fine.

One question though: All these generated pages have lost their white backgrounds and the "Learn More" links are no longer there to fold up & reveal content. Is that intentional? 

Old: https://www.dropbox.com/s/erfjuwspcj2sher/Screenshot%202016-10-20%2016.35.42.png?dl=0

New: https://www.dropbox.com/s/jd5kmamrgq8cre4/Screenshot%202016-10-20%2016.36.13.png?dl=0

If that's all copacetic, good to self-merge

**Comment by ckprice** [comment]
> and the "Learn More" links are no longer there to fold up & reveal content.

This was an ask from legal, so we may want to get it back in.

**Review by ckprice — DISMISSED** [review]
I think this should be blocked until we can fix the toggle, or confirm with legal that it's not needed anymore.

**Comment by johngruen** [comment]
@ckprice @lmorchard i totally forgot to check the content toggles. The color change is by design...I figured it would be nice if these pages better matched all the others. 

I'll look into re-adding the toggles first thing tomorrow.

**Pull request merged**
