### PR TITLE
Experimenting with package-lock and dependencies [WIP]

### PR DESCRIPTION
**Pull request by devinreams**
Follow up to #3800 

As @lmorchard said: 

>The `package-lock.json` file should ultimately be derived from installations based on `package.json`. Doing an `npm install` without a `package-lock.json` *does* install everything - just not the precise locked versions we had in `package-lock.json`. So, if we're now using an old restored version of `package-lock.json` - this issue may return the next time we update it along with a change to `package.json`

Yeah... and looking at the output of the builds after the lock file was removed didn't clue me in to any obvious missing items. I wasn't quite sure how to best start reconciling but there's certainly something fishy..

>Might need to do a little more investigation, since I suspect there might be a newer version of something in our dependencies breaking something that the older version of `package-lock.json` could mask

Perhaps. This branch is a quick start to troubleshoot this further.

The first commit is the result from my local machine:

```
rm -rf node_modules
npm install
git commit
```

Update: I know @meandavejustice is looking at dependencies now too, so this is all mostly thought experiment and just trying to dial in and find the core issue.

### CODE REVIEW

**Comment by MozillaTestPilotStorybook** [comment]
# Storybook Deployment
Pull Request: http://testpilot-storybook.dev.mozaws.net/pull/3801/index.html
Commit: http://testpilot-storybook.dev.mozaws.net/64e23ea757ec27d816d21be7dad211759e94901a/

**Comment by MozillaTestPilotStorybook** [comment]
# Storybook Deployment
Pull Request: http://testpilot-storybook.dev.mozaws.net/pull/3801/index.html
Commit: http://testpilot-storybook.dev.mozaws.net/1db96f179d8fc242ab82590682c602432d28fc32/

**Comment by MozillaTestPilotStorybook** [comment]
# Storybook Deployment
Pull Request: http://testpilot-storybook.dev.mozaws.net/pull/3801/index.html
Commit: http://testpilot-storybook.dev.mozaws.net/c373ac65ffdec759aef10039ed42944ce202f8c7/

**Comment by MozillaTestPilotStorybook** [comment]
# Storybook Deployment
Pull Request: http://testpilot-storybook.dev.mozaws.net/pull/3801/index.html
Commit: http://testpilot-storybook.dev.mozaws.net/21764663b2154fd4e2fe9db507199f2724e7b324/

**Comment by MozillaTestPilotStorybook** [comment]
# Storybook Deployment
Pull Request: http://testpilot-storybook.dev.mozaws.net/pull/3801/index.html
Commit: http://testpilot-storybook.dev.mozaws.net/b1195c946feff1d64501be73ff0ba1333e9cdb1c/

**Comment by MozillaTestPilotStorybook** [comment]
# Storybook Deployment
Pull Request: http://testpilot-storybook.dev.mozaws.net/pull/3801/index.html
Commit: http://testpilot-storybook.dev.mozaws.net/05cf7add31aba15429663d44e5aa1502f8bf1e12/

**Comment by MozillaTestPilotStorybook** [comment]
# Storybook Deployment
Pull Request: http://testpilot-storybook.dev.mozaws.net/pull/3801/index.html
Commit: http://testpilot-storybook.dev.mozaws.net/cfa5c00c34b329c9bc7fc34e1adae786c1a1ac94/

**Comment by devinreams** [comment]
@lmorchard OK I've just been playing with this between some meetings and think this branch is stable enough for any environment to:

```
rm -rf node_modules
npm install
npm run test
npm run start
```

and will "Just Work".

~Even this worked for me (on macOS):~

```
rm -rf node_modules
rm package-lock.json
npm install
npm run test
npm run start
```



~So... that all kinda makes me think I found the missing dependencies that were hiding somewhere in package-lock (but not in package). Up to ya'll if you think its worth merging this but there are lessons buried in these here commits.~

I know @meandavejustice will have some dependency updates too so may be best to cherry-pick off here anything that seems useful. Again up to all ya'll if you think anything here is useful. 😁

**Comment by devinreams** [comment]
I lied, browser was cached and when I deleted package-lock.json the site images broke again. So. Yay. 👻

**Comment by MozillaTestPilotStorybook** [comment]
# Storybook Deployment
Pull Request: http://testpilot-storybook.dev.mozaws.net/pull/3801/index.html
Commit: http://testpilot-storybook.dev.mozaws.net/72ab344d13637072fab465d1c81185d1c5c093da/

**Comment by meandavejustice** [comment]
we have a fix for this coming this afternoon

**Comment by fzzzy** [comment]
@devinreams Thank you for originally diagnosing the issues with the missing package-lock! I think we've got the weirdness related to this under control now.

**Pull request closed without merging**
