### PR TITLE
Retire auto-deployment to Elastic Beanstalk

### LINKED ISSUE #404: Retire support for idea-town-dev in Elastic Beanstalk
Renaming the project in various places has broken the CI duct tape that leads to Elastic Beanstalk.

<strike>Is idea-town-dev.elasticbeanstalk.com useful? If so, it should get fixed. If not, it should get cleaned out of the project</strike>

Going to retire idea-town-dev, because we're moving to a deployment model supported by ops.

### PR DESCRIPTION
**Pull request by lmorchard**
- Remove Docker build & deployment sections from .travis.yml
- Remove Elastic Beanstalk config template & build scripting

closes #404

### CODE REVIEW

**Comment by pdehaan** [comment]
Do we need to tweak the addon and republish a new version? /cc @meandavejustice 
1. [/addon/dev-prefs.json:4](https://github.com/mozilla/testpilot/blob/ebc2e42b034659f2e1f0b379515bf6259a09914b/addon/dev-prefs.json#L4)
2. [/addon/index.js:43](https://github.com/mozilla/testpilot/blob/334d776393425df52564d9f1cad99c2b882ed736/addon/index.js#L43)
3. [/addon/package.json:44](https://github.com/mozilla/testpilot/blob/ebc2e42b034659f2e1f0b379515bf6259a09914b/addon/package.json#L44)

**Comment by pdehaan** [comment]
Also, any EBS references in the [.dockerignore](https://github.com/mozilla/testpilot/blob/ebc2e42b034659f2e1f0b379515bf6259a09914b/.dockerignore#L17-L18) or [.gitignore](https://github.com/mozilla/testpilot/blob/ebc2e42b034659f2e1f0b379515bf6259a09914b/.gitignore#L21-L26) files.

**Comment by meandavejustice** [comment]
@lmorchard Would you wanna update the addon in this pr or should I open a separate one?

**Comment by lmorchard** [comment]
Should probably update the addon separately, after we've sorted out deployment for prod & stage

This PR is _just_ for turning off elastic beanstalk, and I didn't want to bundle much more than that into it

**Comment by meandavejustice** [comment]
Looks good, I opened a issue #415 for removing the refs from the addon.

**Pull request merged**
