### PR TITLE
Fix typo, update link

### PR DESCRIPTION
**Pull request by ckprice**
I'll delete branch after this merges.

### CODE REVIEW

**Comment by pdehaan** [comment]
Me thinks that ./docs/ broken link was due to the recent refactor in #423

**Comment by ckprice** [comment]
Travis is [crying](https://travis-ci.org/mozilla/testpilot/jobs/111051993)

`244: ERROR: InvocationError: '/usr/bin/make -C docs html'`

Looking into it.

**Comment by meandavejustice** [comment]
That command needs to be removed from tox.ini now since we no longer build docs

**Comment by meandavejustice** [comment]
This is actually my fault for merging the `docs/` pr before letting travis build, whoops

~~I'll open up a pr for this rn.~~ fixed in https://github.com/mozilla/testpilot/pull/426

**Comment by meandavejustice** [comment]
@ckprice This is just need a quick rebase with master, then it should build fine again.

**Pull request merged**
