### PR TITLE
Fixed a few typos via markdown-spellcheck

### PR DESCRIPTION
**Pull request by pdehaan**
Via <kbd>$ npx markdown-spellcheck 'docs/**/*.md' --en-us -a -n -x</kbd>

### CODE REVIEW

**Comment by meandavejustice** [comment]
@pdehaan This is great.

Only question: Do we want to add another config file to the repo? `.spelling`

**Comment by pdehaan** [comment]
@meandavejustice depends if anybody else wants to run the spellchecker. I’m fine deleting it (and keeping it locally), or adding the config *and* markdown spellchecker as a devDep. Your call.

**Comment by meandavejustice** [comment]
@pdehaan let's just delete the config from the repo and keep the changes :)

**Comment by pdehaan** [comment]
> let's just delete the config from the repo and keep the changes :)

Done.

**Pull request merged**
