### PR TITLE
Update Lockbox launch time to 6 AM Pacific

### PR DESCRIPTION
**Pull request by devinreams**
Per @sandysage @marniepw @johngruen this will go live at 6 AM Pacific, 7 AM Mountain, 1 PM GMT/UTC.

### CODE REVIEW

**Comment by MozillaTestPilotStorybook** [comment]
# Storybook Deployment
Pull Request: http://testpilot-storybook.dev.mozaws.net/pull/3700/index.html
Commit: http://testpilot-storybook.dev.mozaws.net/08f1b5fac389064e493a53a7636432ab109c3381/

**Comment by devinreams** [comment]
The App in the App Store is also set to automatically be released at 6 AM Pacific / 7 AM Mountain now:

app_store_connect

**Comment by MozillaTestPilotStorybook** [comment]
# Storybook Deployment
Pull Request: http://testpilot-storybook.dev.mozaws.net/pull/3700/index.html
Commit: http://testpilot-storybook.dev.mozaws.net/97972497cfe1ddce94827b37dfc59cb692792778/

**Comment by devinreams** [comment]
Hah whoops, I think I accidentally created this PR against `l10n` not `master`. Oh well, once #3701 gets merged to `master` we're all good. 👌

**Comment by SoftVision-CiprianMuresan** [comment]
Hey, I've confirmed that the Lockbox experiment correctly appears as soon as the clock hits our planned Launch time on the staging server.

**Pull request merged**
