### PR TITLE
Restore integration tests in CircleCI

### PR DESCRIPTION
**Pull request by lmorchard**
This PR is on a branch of the main Test Pilot repo, so it should be able to accept commits & PRs from a bunch of us. Let's see if we can work here and improve things for issue #2541

### CODE REVIEW

**Comment by b4handjr** [comment]
So what is going to be judge of when we can turn these back on? Looking through all the builds, out of 100 builds there was a timeout error twice, and ENOSPC errors like 10 times or so.

**Comment by lmorchard** [comment]
> So what is going to be judge of when we can turn these back on?

That's a good question. We've got a status meeting in Test Pilot Vidyo in about 20 minutes, where I'll bring this up. I'm hoping we can re-enable for at least release Firefox, and maybe throw in #2542 to skip tests for Pontoon commits so we hit CircleCI less often overall. There are more improvements for #2536 but I don't want to have us leave them disabled for long

**Comment by b4handjr** [comment]
Speaking with another QA dev, it seems that running the tests in parallel can sometimes cause a race condition between geckodriver/firefox starting and the test harness. I have a PR almost ready to remove parallel testing and to enable a html report to always be collected.

**Comment by lmorchard** [comment]
Tweaking this PR to re-enable for release Firefox. Let's see how long the test run takes.

**Comment by b4handjr** [comment]
Before we merge I want to add some extra things. I can just push to your branch correct?

**Comment by lmorchard** [comment]
> Before we merge I want to add some extra things. I can just push to your branch correct?

I think so... if not, say because you don't have permission to push to test pilot branches, I think you can submit a pull request to this branch instead of master. Gets tangly & confusing, but should be okay

**Comment by b4handjr** [comment]
That failure is because the github api only allows for 50 requests an hour unless you config it to use oauth or something like that.

**Pull request merged**
