### PR TITLE
Remove version and modified date from experiment page

### LINKED ISSUE #1523: Remove experiment version number from details page
Currently when we push a new version of an experiment XPI to Test Pilot, we need to update the experiment's YAML file with the new version, and then upstream those to stage and prod.

If we remove the experiment's version number from the Test Pilot site, we'd just need to update the experiment's XPI in S3 and update the update.json.

### PR DESCRIPTION
**Pull request by meandavejustice**
- fixes #1523
- update ExperimentPage-test
- update localization data
- remove `version` and `modified` fields from experiment yaml files

version-updates-txp

cc/ @clouserw

### CODE REVIEW

**Comment by ghost** [comment]
Whacking the version and date is great, but why the changelog?  Also, can you remove the version/date fields from the experiment files and documentation?

**Comment by meandavejustice** [comment]
@wresuolc ~~I sure can,~~(updated)
I didn't remove the changelog, just gave it it's own section, see screenshot

**Comment by ckprice** [comment]
Pulled this down, and everything works as expected.

We (unfortunately) reference these fields in 3 different places

- https://github.com/mozilla/testpilot/blob/master/docs/content/reference.md
- https://github.com/mozilla/testpilot/blob/master/docs/content/template.yaml
- https://github.com/mozilla/testpilot/blob/master/content-src/experiments/dev-example.yaml (updated in this PR)

@meandavejustice we should probably remove these from the other two or re-organize these docs.

**Comment by meandavejustice** [comment]
good catch @ckprice, just fixed those up as well

**Review by ckprice — APPROVED** [review]

**Pull request merged**
