### PR TITLE
make check a sprite

### LINKED ISSUE #3048: [Newsletter forms] The privacy notice message checkbox shortly disappears after hover, check and hover away actions
**[Affected versions]:**
- Firefox 56.0.2 and above

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Prerequisites]:**
- Following 5 prefs have been set or added on a new profile: "extensions.legacy.enabled = true" "xpinstall.signatures.required = false" "testpilot.env = dev" "extensions.webapi.testing = true" "extensions.install.requireBuiltInCerts = false".

**[Steps to reproduce]:**
1. Open Firefox browser and navigate to https://testpilot.dev.mozaws.net page.
2. Scroll down to the page until you reach the "Newsletter" section.
3. Click on the section text box and enter at leas one character.
4. After the privacy notice checkbox appear, slowly hover it and observe its behavior.
5. Click the checkbox and observe its behavior.
6. Hover away the checkbox and observe it's behavior.

**[Expected result]:**
- Step 4: The checkbox border becomes blue without any display issues.
- Step 5: The checkbox is correctly checked without any display issues.
- Step 6: The checkbox border looses the blue border without any display issues.

**[Actual result]:**
- Step 4: The checkbox shortly disappears before the hover effect occurs.
- Step 5: The checkbox shortly disappears again before the check mark is displayed.  
- Step 6: Again, the checkbox shortly disappears when hovered away. 

**[Notes]:**
- These 3 behaviors only occur the first time the above actions are performed. But sadly they reappear in a new tab or after browser restart. 
- This behavior also occurs on the Newsletter dialog flow after you install Test Pilot add-on.
- Here is a recording of the issue: https://goo.gl/pg7dDP.

### PR DESCRIPTION
**Pull request by johngruen**
Fixes #3048

### CODE REVIEW

**Comment by johngruen** [comment]
@fzzzy i think this is failing for reasons unrelated to the content of this PR...can you confirm?

**Comment by pdehaan** [comment]
Not sure what the 19k lines of package-lock.json file changes are, or if they're needed in this PR (since package.json didn't seem to change at all).
  
---

~~**UPDATE 1:** Me definitely thinks that package-lock.json should be in the .gitignore file.~~
~~**UPDATE 2:** Actually, I think this is the better/correcter approach: https://codeburst.io/disabling-package-lock-json-6be662f5b97d~~

```sh
echo 'package-lock=false' >> .npmrc
echo 'package-lock.json' >> .gitignore
```

**UPDATE 3:** Nevermind. See #3290; "Commit package-lock.json files".

**Comment by fzzzy** [comment]
@johngruen can you just remove the package-lock from this pr?

**Comment by meandavejustice** [comment]
@fzzzy @johngruen I just removed the `package-lock.json` and pushed, should pass now

**Comment by johngruen** [comment]
Thanks @meandavejustice!

**Pull request merged**
