### PR TITLE
Added a few install tests and enable tests

### LINKED ISSUE #3088: Write an integration test to cover uninstalling the addon (the retire page)
We test installing the add-on in the integration tests, but we don't test uninstalling it. We should.

### PR DESCRIPTION
**Pull request by b4handjr**
Fixes #3088

New tests:
1: Disable experiment
2: Install the TestPilot experiment and enable an experiment from the experiment page
3: Install TestPilot extension from the bottom install button
4: Check the install button is not shown when the TestPilot extension is installed

### CODE REVIEW

**Comment by fzzzy** [comment]
@jrbenny35 Hey, this branch has conflicts now. Sorry for leaving it for so long and having it go stale. Can you rebase and fix conflicts, and ping us to review it?

**Comment by meandavejustice** [comment]
We should also make sure we are testing install from the featured experiment section now that those tests were just added.

They can be added later though if you like, we should just create an issue for it

**Comment by jrbenny35** [comment]
@fzzzy Can we tag this for a future merge?

**Comment by b4handjr** [comment]
> We should also make sure we are testing install from the featured experiment section now that those tests were just added.

Good idea, I can add that after these merge.

**Review by fzzzy — APPROVED** [review]

**Comment by meandavejustice** [comment]
Thanks @jrbenny35 !!

**Pull request merged**
