### PR TITLE
Use sentence case capitalization, rather than all caps, for liability statements

### LINKED ISSUE #1002: Use sentence case capitalization, rather than all caps, for liability statements
@ckprice

### PR DESCRIPTION
**Pull request by pdehaan**
Just a plain ol' paragraph now, but can wrap it in bold text if we want to give it slightly more emphasis.

Fixes #1002

### CODE REVIEW

**Comment by johngruen** [comment]
Hey @pdehaan thanks for doing this! I cc'ed you on an email to the legal team to confirm we can get away with these changes.

**Comment by pdehaan** [comment]
Ref: https://bugzilla.mozilla.org/show_bug.cgi?id=1281242

It's an internal/confidential bug, but here's some feedback that we got (which I've addressed and pushed onto this PR):

> In addition, I reviewed the pull request and there are a bunch of sentences that need to be fixed to start with a capital letter:
> 
> line 34:
> - "to the extent permitted by law"
> - "you bear the entire risk"
> - "this limitation will apply"
> - "some jurisdictions do not allow"
> 
> line 36:
> - "the collective liability"
> - "some jurisdictions"

**Comment by pdehaan** [comment]
@johngruen I just made the paragraphs bold to make them more **conspicuous**, but we can see if we can embed some HTML in the Markdown (if the parser doesn't strip it) if we want to try attaching CSS classes to the paragraphs in question.

**Comment by johngruen** [comment]
@pdehaan can you squash your commit?

**Comment by johngruen** [comment]
Otherwise R+ pending comment from Elvin on that Bugzilla bug.

**Comment by johngruen** [comment]
FWIW: 

bold-copy

**Pull request merged**
