### PR TITLE
Build a wrapper for submitExternalPing()

### PR DESCRIPTION
**Pull request by lmorchard**
- Add small example add-on showing how to use the ping messaging
- Switch to sdk/system/events for cleaner access to nsIObserver
- Remove lib/authRequest.js for now, because metrics pings do not go to
  the Test Pilot server any more. (Feedback also now does nothing)
- Do not ping for every message that the addon sends to web content
- Small bugfix for isTestpilotAddonID
- Misc reorganizing in require()'s at the top

Issue #479

### CODE REVIEW

**Comment by lmorchard** [comment]
So, I think this works. But, a couple open questions:
- This does pass a message event from an example experiment add-on to the Test Pilot add-on, but [my pings are probably bogus examples](https://github.com/mozilla/testpilot/pull/538/files#diff-e5efab61baef2675973f8a95bc256e6cR28). Guessing this is where each experiment should define a consistent ping schema and stick with it.
- No docs for this yet, but I wanted to make sure the code was solid before writing them.
- I was tempted to (re)start a shared library for the `sendMetricsPing` function, but it's very tiny.

**Comment by lmorchard** [comment]
<strike>Oh yeah, and this doesn't include the once-a-day `testpilot` ping</strike>

**Comment by lmorchard** [comment]
Just added code to send the once-a-day `testpilot` ping, with payload kept up to date with experiment installs & uninstalls.

**Comment by lmorchard** [comment]
@chuckharmston - you might want to peek at [the `sendMetricsPing` function in the example add-on](https://github.com/mozilla/testpilot/pull/538/files#diff-e5efab61baef2675973f8a95bc256e6cR5) in this PR to see how the ping will work. What to send as the actual ping payload is still kind of a moving target, though.

**Comment by lmorchard** [comment]
@meandavejustice / @chuckharmston - have time to peek at this, have any thoughts?

**Comment by meandavejustice** [comment]
This looks great to me, and the addon builds locally. We'll review the actual pings to telemetry once we get that hooked up from the otherside. :+1:

**Pull request merged**
