### PR TITLE
Ensure page content even without grad report

### LINKED ISSUE #2580: If there's no Grad Report at graduation, render normal content with a warning
Doesn't look like we're going to have grad reports quite ready for wednesday. Right now the whole left column of the page is blank. We should at least show the intro text with a notice that the grad report is coming soon.

### PR DESCRIPTION
**Pull request by johngruen**
Fixes #2580

### CODE REVIEW

**Comment by johngruen** [comment]
#2580

**Comment by ghost** [comment]
I don't think this is critical since we haven't pushed any notices out yet.  I think at this point we can just push the graduation reports and the notices and stuff all at once.  Our graudation alerts aren't very effective as-is anyway.

/cc @flodolo for new l10n

**Comment by fzzzy** [comment]
@flodolo There are two new strings here.

**Comment by flodolo** [comment]
> @flodolo There are two new strings here.

Can't spot anything wrong with them, thanks.

**Pull request merged**
