### PR TITLE
Require ENABLE_PONTOON=1 during frontend build to include Pontoon JS in pages

### LINKED ISSUE #1356: Remove pontoon.js from production instance
The [pontoon.js](https://developer.mozilla.org/en-US/docs/Implementing_Pontoon_Mozilla) script is required to allow in-page localization of Test Pilot with [Pontoon](https://pontoon.mozilla.org/).

It only has to be loaded in the environment that is used for in-page localization, e.g. staging server. You can remove it from the production instance.

### PR DESCRIPTION
**Pull request by lmorchard**
Fixes #1356

### CODE REVIEW

**Comment by lmorchard** [comment]
This should exclude the Pontoon script tag by default on all pages, _unless_ ENABLE_PONTOON=1 is set during frontend build. That's enabled in this PR for develpoment-static branch, but it should be off for any other deployments in the future.

You can test this locally by running gulp and verifying that there's no Pontoon script tag on the page. Restart with `ENABLE_PONTOON=1 gulp` and the script tag should appear.

**Review by chuckharmston — CHANGES_REQUESTED** [review]
This looks great!

Only nit: this seems like the sort of thing we should be documenting.

**Comment by ghost** [comment]
Thanks for cooking this up, Les and for reviewing it, Chuck

**Comment by lmorchard** [comment]
> Only nit: this seems like the sort of thing we should be documenting.

Definitely a good point. One caveat is that the static build system isn't documented at all yet, so there's not really a good place to put just the mention of this flag right now. Hoping to work on those docs today for #1350

**Comment by lmorchard** [comment]
May collide with PR #1366, but I added a section to deployment docs describing how ENABLE_PONTOON is used.

**Review by chuckharmston — APPROVED** [review]

**Pull request merged**
