### PR TITLE
fixed unit test reporting on circleci

### LINKED ISSUE #3455: failing unit tests pass circleci

### PR DESCRIPTION
**Pull request by dannycoates**
fixes #3455

### CODE REVIEW

**Comment by MozillaTestPilotStorybook** [comment]
# Storybook Deployment
Pull Request: http://testpilot-storybook.dev.mozaws.net/pull/3465/index.html
Commit: http://testpilot-storybook.dev.mozaws.net/55585757cf580215587c6f9e5640041f4b68cd19/

**Comment by MozillaTestPilotStorybook** [comment]
# Storybook Deployment
Pull Request: http://testpilot-storybook.dev.mozaws.net/pull/3465/index.html
Commit: http://testpilot-storybook.dev.mozaws.net/2c590194bb739ceba072b7fe6aed8a0316a98953/

**Comment by dannycoates** [comment]
https://circleci.com/gh/mozilla/testpilot/8997?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

Failed as expected

**Comment by MozillaTestPilotStorybook** [comment]
# Storybook Deployment
Pull Request: http://testpilot-storybook.dev.mozaws.net/pull/3465/index.html
Commit: http://testpilot-storybook.dev.mozaws.net/7f0a1253cf831f6c512d0bf9b5e7e3688b625a8f/

**Pull request merged**
