### PR TITLE
Hide testpilot promo header when experiment graduates

### LINKED ISSUE #2899: [Dev] Graduated experiments details page wrongly contain the enable option and most of them can be enabled together with Test Pilot
**[Notes]:**
- It seems that this is a regression caused by #2875 PR.
- The experiments that had a final report no longer have it (Universal Search, NoMore404s and Tracking Protection).
- With the install functionality returned to the graduated experiments, you can enable all graduated experiments except Universal Search.

**[Affected versions]:**
- Nightly 58.0

**[Affected Platforms]:**
- All Windows
- All mac OS
- All Linux

**[Prerequisites]:**
- Following 5 prefs have been set or added on a new profile: "extensions.legacy.enabled = true" "xpinstall.signatures.required = false" "testpilot.env = dev" "extensions.webapi.testing = true" "extensions.install.requireBuiltInCerts = false".

**[Steps to reproduce]:**
1. Open Firefox browser with the profile from prerequisites and navigate to https://testpilot.dev.mozaws.net page.
2. Scroll down on the Homepage and click the "View Past Experiments" button under the last active experiment.
3. After past experiments cards are displayed, open them all in new tabs.
4. Select each tab and observe the graduated experiments details page.

**[Expected result]:**
- The graduated experiment old details page is displayed without the install part that is displayed for active experiments.

**[Actual result]:**
- Graduated experiments details pages are wrongly containing the install part along with Test Pilot add-on.

grad experiment detaisl page
enabled graduated

### PR DESCRIPTION
**Pull request by lmorchard**
Fixes #2899

### CODE REVIEW

**Comment by lmorchard** [comment]
# Storybook Deployment
Pull Request: http://testpilot-storybook.dev.mozaws.net/pull/2901/index.html
Commit: http://testpilot-storybook.dev.mozaws.net/09e4e17a6ff705f8ed3ce7216bb0fe272c702030/

**Comment by meandavejustice** [comment]
@lmorchard Happy to take care of this one once conflicts are resolved

**Comment by lmorchard** [comment]
# Storybook Deployment
Pull Request: http://testpilot-storybook.dev.mozaws.net/pull/2901/index.html
Commit: http://testpilot-storybook.dev.mozaws.net/695423b5155d8d541a45d56c2c21efb848e6ae67/

**Comment by meandavejustice** [comment]
@lmorchard checked this out locally and it all looks good, can you fix history with a rebase then it's good to merge

**Comment by lmorchard** [comment]
> can you fix history with a rebase then it's good to merge

We changed the repo config on github to do this automatically with the "Squash & Merge" button, so we don't have to do rebases anymore by hand

**Comment by meandavejustice** [comment]
wasn't sure if I could trust that, thanks for the info :)

**Pull request merged**
