### PR TITLE
Add page and newsletter sign up Integration Tests

### PR DESCRIPTION
**Pull request by b4handjr**
Adds a few sign-up and page tests. Also removed the until bash script as pytest-base-url will now wait for the server to start.

### CODE REVIEW

**Comment by b4handjr** [comment]
For some reason circleci isn't running the tests...

**Comment by b4handjr** [comment]
Github is having some issues

**Comment by fzzzy** [comment]
@jrbenny35 Let me know when you are ready for me to look at this. Should probably rebase and squash.

**Comment by b4handjr** [comment]
@fzzzy Please check it out now

**Comment by lmorchard** [comment]
Looks good to me. Going to merge and update the [restore-integration-tests](https://github.com/mozilla/testpilot/tree/restore-integration-tests) branch, so these tests should run there while master has them disabled.

**Comment by fzzzy** [comment]
Thanks @lmorchard.

**Pull request merged**
