### PR TITLE
Upgrade react, react-dom and react-markdown

### LINKED ISSUE #3859: Update react, react-markdown & react-dom
Having an issue where we are getting an error saying that "View component has a render method but isn't extending React.Component". But our View component _is_ extending `React.Component` :man_shrugging: 

Haven't found any directly relevant issues yet.

### PR DESCRIPTION
**Pull request by meandavejustice**
fixes #3859

### CODE REVIEW

**Comment by lmorchard** [comment]
Saw a small package-lock.json merge conflict (package-lock 😠). ~Tried resolving it, hopefully didn't break anything.~ Looks like something broke. 😞 Oh, looks like my dev env was using the wrong version of node - hopefully *this* time I've fixed it and resolved the conflict...

**Comment by lmorchard** [comment]
Huh, looked like tests were passing, but now the conflicting commit is back

**Comment by meandavejustice** [comment]
@lmorchard I think I got it fixed up now

**Comment by lmorchard** [comment]
Oh, heh, I was working on fixing it too

**Pull request merged**
