### PR TITLE
Do not re-build static site for every integration test run

### LINKED ISSUE #2525: Build site only once to speed up integration tests
With PR #2518, we now test the site against Firefox release, dev-edition, and nightly. But, for each of those test runs, we rebuild the site's static content every time with `npm start`. 

I *think* we could speed this up by just doing `npm run server` instead. Assuming it re-uses the site built earlier in [the `build-frontend` step](https://github.com/mozilla/testpilot/blob/master/bin/circleci/build-frontend.sh), this might be an easy win. But, it could use some investigation

### PR DESCRIPTION
**Pull request by lmorchard**
- Build the site earlier, reuse the result in tests

- Add `set -ex` to test scripts to echo commands & fail fast

Fixes #2525

### CODE REVIEW

**Comment by lmorchard** [comment]
This doesn't speed things up *nearly* as fast as I'd hoped. Sigh.

**Comment by b4handjr** [comment]
We could start the server once and just install the firefox versions after each test

**Comment by b4handjr** [comment]
Or only test all 3 versions on a deployment

**Comment by lmorchard** [comment]
The server itself doesn't really take much time to start up. And I hate to exclude tests until deployment, because that's the worst time to get surprises. (i.e. when we're trying to hustle something out the door) Probably good to just consider this PR an incremental improvement as-is, and we can keep poking at it.

**Comment by b4handjr** [comment]
Makes sense. R+

**Review by b4handjr — APPROVED** [review]

**Pull request merged**
