### PR TITLE
Issue #47: Remove client-side build machinery from server repo

### LINKED ISSUE #47: Remove client-side gulp build chain from this repo
[The client-side gulp shenanigans have moved](https://github.com/mozilla/idea-town-app). Remove them from this repo.

### PR DESCRIPTION
**Pull request by lmorchard**
Client-side stuff [has moved](https://github.com/mozilla/idea-town-app), so stop trying to make that happen in the server repo.

Fixes #47

### CODE REVIEW

**Comment by meandavejustice** [comment]
lgtm :+1:

**Comment by pdehaan** [comment]
@lmorchard: What about other files in the root directory?
Do we need to kill any of these:
- [ ] .gitignore's:
  - [x] node_modules/
  - [ ] media/
  - [ ] static/
  - [ ] client-build/
  - [ ] client-src/
- [x] .eslintrc

Actually, maybe that's it.

**Comment by GitCop** [comment]
There were the following issues with your Pull Request
- Commit: cf09df8df99006b61ed8911bc56144366e47636d
  - Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mozilla/idea-town-server

---

This message was auto-generated by https://gitcop.com

**Comment by pdehaan** [comment]
DOH! I just noticed that the [README.md](/README.md) also mentions gulp and some client stuffs:

> If you change `package.json` to add dependencies for `gulpfile.js`, you must rebuild `client_build`:
> - `docker-compose build client_build`

Not sure if that also needs to be removed (new bug upon request).

**Comment by lmorchard** [comment]
Ironically enough... we're kind of in the process of reverting this removal right now :dancers:

**Pull request merged**
