### PR TITLE
Email footer tweaks

### LINKED ISSUE #3044: Footer Newsletter Photonization - Design vs implementation observed differences
Here are the differences observed:
- [x] Implemented background color is darker than designed.
- [x] ~~Background color should also cover footer links based on design.~~
A different design was made for this area #3225 
- [x] First message displayed on 2 rows (implementation) vs 3 rows (design).
- [x] ~~Hint message from text box has first letter in uppercase (implementation) vs all letters in uppercase (design). As on old implementation.~~
- [x] There is already space between text box and sign up button for privacy message (implementation) vs no space (design). Like on old implementation
- [x] The "Sign Up Now" button font size is 20px (implementation) vs 15px (design).
- [x] The "We will only send you Test Pilot-related information." message font size is 14px (implementation) vs 13px (design).
- [ ] The "We will only send you Test Pilot-related information." message is aligned to center (implementation) vs to left (design).
- [x] The privacy notice message font size is 12px (implementation) vs 13px (design). ~~Also, in the designs, the text exceeds the text box and button, while on current implementation it wraps if modified.~~
- [x] ~~Error message is displayed on the center of the Newsletter section (implementation) vs centered above the text box and pointing at it (design). Also, the design of it is different than the one in designs.~~
Tracked separately in #3042
- [x] I haven't seen the "Sign Up Now" button barberpole animation + "Submitting..." text even with the internet connection down. Also, when clicked, the button remains in "clicked" state after an error occurs.
- [x] Submitted message is displayed on 3 rows (implementation) vs 2 rows (design).

Let me know if you want me to file separate bugs for any of them.

### PR DESCRIPTION
**Pull request by johngruen**
Fixes #3044

### CODE REVIEW

**Comment by johngruen** [comment]
Note, i did this on top of #3245 so we should probably fix that first.

**Comment by SoftVision-PaulOiegas** [comment]
Brought the branch locally and tested about half of the changes, will continue tomorrow with the rest. However, I have noticed on thing. Isn't there a bit to much space between the "Sign Up Now" button and "We will only send you Test Pilot-related information." ? 

The space was indeed added in the designs, but maybe it's a bit to much as it is right now. On production server there is almost none on the old implementation.

**Comment by johngruen** [comment]
@SoftVision-PaulOiegas idk, i didn't touch that code in this PR

**Comment by SoftVision-PaulOiegas** [comment]
After round 2 of testing, there is only 1 difference that is still visible if we exclude the one with the space mentioned above.
- The "We will only send you Test Pilot-related information." message is aligned to center (implementation) vs to left (design).
Should start together with the "Sign Up Now" button

**Comment by fzzzy** [comment]
@SoftVision-PaulOiegas I'd like to just merge this. If there are any remaining bugs please file a new issue.

**Pull request merged**
