### PR TITLE
Turn off enable button animation when download ends in error

### LINKED ISSUE #1352: When a download fails the button remains in the enabling state.
[As reported](https://github.com/mozilla/testpilot/issues/1307#issuecomment-246845942) by @dannycoates in #1307:

> When a download fails the button remains in the enabling state.
> 
> screen shot 2016-09-13 at 2 54 14 pm

### PR DESCRIPTION
**Pull request by lmorchard**
Fixes #1352

### CODE REVIEW

**Comment by lmorchard** [comment]
@dannycoates - I think this fixes the download button thing

**Comment by lmorchard** [comment]
Updated commit to fix some linting goofs

**Review by dannycoates — APPROVED** [review]
The logic is sort of confusing, but it works. Onward and upward!

**Comment by lmorchard** [comment]
Yeah, I kind of think most of what I'm doing here with looking up the experiment from slug should be handled somehow in the router, but my React-fu isn't strong enough to figure that out yet

**Pull request merged**
