### PR TITLE
Update API used to find hostname for WebExtension BroadcastChannels

### LINKED ISSUE #2968: Update extension api use
This is blocking https://bugzilla.mozilla.org/show_bug.cgi?id=1291399

https://github.com/mozilla/testpilot/blob/a732512053cc3cb64d408918dcff85d8cb96a083/addon/src/lib/channels.js#L15

You need to replace the uuid getter to do something like:

const {WebExtensionPolicy} = Cu.getGlobalForObject(Cu.import("resource://gre/modules/Extension.jsm", {}));
let {mozExtensionHostname} = WebExtensionPolicy.getByID(gAddon.id);
baseurl = `moz-extension://${mozExtensionHostname}/`,

### PR DESCRIPTION
**Pull request by lmorchard**
Also skip creating channels for experiments that aren't installed,
because the new API won't yield a hostname (not sure how this was even
working before)

Fixes #2968

### CODE REVIEW

**Comment by lmorchard** [comment]
This is also a bit hard to test, since it's hacks all the way down. Best way is probably to build the add-on, temporarily load in an unbranded build with about:debugging, then enable Snooze Tabs from one of the environments. 

There should be a message somewhere in the Browser Console about the channel opening for Snooze Tabs. Also, you should see metrics pings from Snooze Tabs going through in log messages when opening the experiment's panel & various other interactions.

Also filed #2978 to remove this code altogether someday (hopefully) soon

**Comment by fzzzy** [comment]
I'll try to review this today.

**Comment by lmorchard** [comment]
Updated - turns out the new approach to getting the psuedo-hostname for a webextension BroadcastChannel doesn't work if the extension wasn't already installed. So, we need to open them when experiments are installed.

Some more detailed steps to run this through its paces:

* build the add-on with `cd addon && npm run package:dev` and use about:debugging

* enable Snooze Tabs

* open Browser Console (i.e. not Web Console) and look for log messages like these to verify the channel opened: 
```
[TESTPILOT v2] (background) pubsub bootstrap.addonManager.installed Object { topic: "installed", addon: Object }  background.js:86
[TESTPILOT v2] (bootstrap) openChannel snoozetabs@mozilla.com testpilot-telemetry  bootstrap.js:93
[TESTPILOT v2] (bootstrap) createChannelForAddonId testpilot-telemetry snoozetabs@mozilla.com b0fa2cd3-a400-44ad-bd3a-78a6b21b9430  bootstrap.js:93
[TESTPILOT v2] (bootstrap) pubsub bootstrap.webExtensionAPI.openChannel Object { sendReply: function (), message: Object, sender: Object }
```

* then, click the snooze tabs toolbar button to open the panel. That should cause log messages like these, which indicate a successful Telemetry ping: 
```
SnoozeTabs (FE <SnoozePopup>) fetched entries false Object {  }  snooze-content.js:2
SnoozeTabs (BE) backend received panelOpened undefined  background.js:1
SnoozeTabs (Metrics) sendEvent 99c6f83c-4b3a-47f1-81a8-7a5fac85b4dc Object { event: "panel-opened" }  background.js:1
[TESTPILOT v2] (bootstrap) pubsub bootstrap.channels.testpilot-telemetry Object { subject: "snoozetabs@mozilla.com", topic: "testpilot-telemetry", payload: Object }  bootstrap.js:93
[TESTPILOT v2] (background) submitExperimentPing args Object { subject: "snoozetabs@mozilla.com", topic: "testpilot-telemetry", payload: Object }  background.js:86
[TESTPILOT v2] (background) pubsub bootstrap.channels.testpilot-telemetry Object { subject: "snoozetabs@mozilla.com", topic: "testpilot-telemetry", payload: Object }  background.js:86
[TESTPILOT v2] (bootstrap) submitExternalPing testpilottest Object { timestamp: 1491, test: "snoozetabs@mozilla.com", version: "1.0.20", payload: Object }  bootstrap.js:93
[TESTPILOT v2] (bootstrap) pubsub bootstrap.webExtensionAPI.submitExternalPing Object { sendReply: function (), message: Object, sender: Object }  bootstrap.js:93
[TESTPILOT v2] (bootstrap) pubsub bootstrap.webExtensionAPI.getTelemetryEnvironment Object { sendReply: function (), message: undefined, sender: Object }  bootstrap.js:93
POST XHR https://incoming.telemetry.mozilla.org/submit/telemetry/f443a88c-ea5f-4d0a-b253-d7fa61e218b5/testpilottest/Firefox/57.0/aurora/20171019140425 [HTTP/1.1 200 OK 449ms]
```

**Comment by fzzzy** [comment]
Verified that it works now after that last commit. Awesome!

**Pull request merged**
