### PR TITLE
Update photonized modals fix #3121 #3120 #3117 #3116

### LINKED ISSUE #3121: The 404 modal does not follow the design
**[Affected versions]:**
- Firefox 57.0.1 and above

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Prerequisites]:**
- Following 5 prefs have been set or added on a new profile: "extensions.legacy.enabled = true" "xpinstall.signatures.required = false" "testpilot.env = dev" "extensions.webapi.testing = true" "extensions.install.requireBuiltInCerts = false".

**[Steps to reproduce]:**
1. Open Firefox browser and navigate to https://testpilot.dev.mozaws.net/404 page.
2. Observe the 404 page modal.

**[Expected result]:**
- The "404" page modal is looking and working as designed.

**[Actual result]:**
- The "404" modal has lots of differences from the design (see attached screenshot).

**[Notes]:**
- See attached screenshot:
404 differences

### PR DESCRIPTION
**Pull request by youwenliang**
Updating the photonized UI to the modals.
Fixing #3121 #3120 #3117 #3116

### CODE REVIEW

**Comment by meandavejustice** [comment]
2017-12-06--09-12-14-1920x1080_scrot

Minor nit here, #3117 has the text as centered where as above the text is aligned left


@youwenliang Everything else looks good to me, happy to merge after this fix is added

**Comment by meandavejustice** [comment]
I went ahead and pushed a commit that centers the content in that modal and cleaned up a couple of properties that were throwing warnings in `buttons.scss` with our sass linter

**Comment by MozillaTestPilotStorybook** [comment]
# Storybook Deployment
Pull Request: http://testpilot-storybook.dev.mozaws.net/pull/3135/index.html
Commit: http://testpilot-storybook.dev.mozaws.net/f4ef566a69b4055953e52be14b510373b961a1d0/

**Comment by johngruen** [comment]
@youwenliang hell yeah!

**Comment by SoftVision-PaulOiegas** [comment]
@youwenliang @johngruen what is the blue buttons right color across all website? I'm asking because we have 2 different colors on the designs provided. One of them was already implemented in the previous merges #0695F9 (from [this design](https://mozilla.github.io/testpilot-assets/Test_Pilot_Website/01_Measurements/Component_20171003/#artboard0)), but with this merge, it changed again everywhere to #0060DF (from [this other design](https://mozilla.github.io/testpilot-assets/Test_Pilot_Website/01_Measurements/Photonized_Txp_Website_Final/#artboard0)).

If we stick to the latest color, we have a bit of inconsistency with the "Feedback" buttons from the experiment cards for example.

image

**Comment by youwenliang** [comment]
The feedback button was also modified in the new spec but I haven't worked on that in this pull request, should be more consistent after the update.

**Comment by SoftVision-PaulOiegas** [comment]
So the darker blue color is the final one for every blue button on the website. Ok, thanks for clarifications.

The light blue ones looked a bit better with the whole photonization in my opinion. Also, those are already on production, so in the next release we'll change them again...

**Pull request merged**
