### PR TITLE
Add social media metadata overrides (closes #761).

### LINKED ISSUE #761: Serve up social metadata so Facebook & friends (and search) show appropriate previews for experiments
Related to #419.

But, more than just adding views to our client-side app. This issue requires that we [add meta headers to our HTML on experiment URL routes on the server side so that Facebook's open graph spider picks them up](https://developers.facebook.com/docs/sharing/best-practices#tags).

### PR DESCRIPTION
**Pull request by chuckharmston**
Getting this up so @johngruen and @ckprice can check out the mechanisms while I polish. Will call for review soon.
## TODO
- [x] Create models and migrations
- [x] Create admin interface
- [x] Validate/test with Twitter and Facebook's respective testing tools.
- [x] Write tests.
- [x] Update demo data fixtures.
## Screenshots

Admin interface

Note that you can override default metadata for arbitrary URLs on the site, not just experiments. Trailing slashes are automatically dealt with, and metadata will be applied with and without them.

Twitter

Since we're likely only using this for experiments, which will benefit from large images, I switched from a Twitter [summary card](https://dev.twitter.com/cards/types/summary) to a [summary large image](https://dev.twitter.com/cards/types/summary-large-image) card for overrides.

Facebook

Facebook on mobile

Ignore the domains on Facebook/mobile; that's an artifact of how I was testing it.

Making good Facebook images will be tricky; they sometimes show it at a 1.9:1 aspect ratio, but will also sometimes crop it to 1:1 depending on the context.

Activity Stream output

Homepage

If no metadata is specified for the current page, a default is used (e.g. what currently exists).

### CODE REVIEW

**Comment by johngruen** [comment]
@chuckharmston this looks fantastic!

**Comment by chuckharmston** [comment]
This is ready for review. r? @lmorchard

**Comment by chuckharmston** [comment]
I can't figure out why the build is failing on `static-src` compilation. I didn't touch it in this PR.

**Comment by lmorchard** [comment]
Looks like it's [failing on python linting](https://circleci.com/gh/mozilla/testpilot/847):

```
./bin/circleci/run-server-unit-tests.sh

+ docker run --net=host -e DEBUG=False -e SECRET_KEY=Foo -e ALLOWED_HOSTS=localhost -e DATABASE_URL=postgres://ubuntu@localhost/circle_test --user root app:build sh -c 'flake8 testpilot && ./manage.py test -v2 testpilot'
testpilot/social/tests.py:3:1: F401 'Client' imported but unused
testpilot/social/tests.py:16:34: E703 statement ends with a semicolon

./bin/circleci/run-server-unit-tests.sh returned exit code 1
```

**Comment by chuckharmston** [comment]
> Looks like it's failing on python linting:

Ah, yeah, I rebuilt it as I made that comment and got different output. A previous build had it failing on an unresolved promise in one of the static files.

**Comment by lmorchard** [comment]
First thoughts overall: It's cool that this is generic by URL, but we only really need this for experiment detail pages.

Would be simpler to add the image fields on the Experiment model and use the existing title, short_title, & description in the meta tags. Also, getting the image fields into the API serializer will make the API-based import task I'm writing in #1250 easier for our transition away from the DB altogether.

**Comment by chuckharmston** [comment]
I built it like this for a few reasons:
- With an eye toward TXP-9, which has us creating a new landing page that may want us to create different metadata.
- You may want different copy on the social media page and the experiment page; content length recommendations may not always mesh with copy on the detail pages, etc.
- Since we're moving away from Django soon, I'd rather build something flexible enough to h handle any new requirements without any further work. Especially since...

> getting the image fields into the API serializer will make the API-based import task I'm writing in #1250 easier

...that'd require one reverse and one additional query. A lot easier than a rewrite here, for sure.

**Comment by lmorchard** [comment]
> With an eye toward TXP-9, which has us creating a new landing page that may want us to create different metadata.
> You may want different copy on the social media page and the experiment page; content length recommendations may not always mesh with copy on the detail pages, etc.

I could be missing something - or have missed a conversation. Can you point me to the issue or mockup that shows a new landing page? My impression is that it's experiment detail page URLs that we want shared, now that they're visible without the add-on. So, this issue was just to add the social media headers to those now-public experiment detail pages.

> Since we're moving away from Django soon, I'd rather build something flexible enough to h handle any new requirements without any further work. Especially since...
> ...that'd require one reverse and one additional query. A lot easier than a rewrite here, for sure.

Not sure what new requirements you mean. Like you wrote, "Since we're likely only using this for experiments" - so a couple of new fields on the Experiment model sounds simpler. Not downplaying everything that's going on in the PR, but it seems like more than we need when we're aiming to reduce things. YAGNI, and all that.

**Comment by chuckharmston** [comment]
I got confused. TXP-9 is to provide a page to share _from_, not to share _to_.

Sigh. 😞

I'll give it another try tomorrow.

**Pull request closed without merging**
