### PR TITLE
Note new version, and my title

### PR DESCRIPTION
**Pull request by ianb**

### CODE REVIEW

**Comment by pdehaan** [comment]
I'm never 100% certain on this l20n stuff, but do we need to change the YAML file _AND_ the job title in the [locales/en-US/experiments.ftl](https://github.com/mozilla/testpilot/blob/814ba1671cd1033e359ebc467d2e3215390aa256/locales/en-US/experiments.ftl#L59) file?

**Comment by chuckharmston** [comment]
Ugh, you're right, that's on me for not catching that. Fix incoming.

**Comment by flodolo** [comment]
Also note, that you want people to update that, you'll need a different data-l10n-id to reforce translation.

**Comment by chuckharmston** [comment]
@flodolo #1902 gets that.

**Pull request merged**
