### PR TITLE
Duplicate mobile trigger button behavior in featured experiment

### LINKED ISSUE #3670: If featured platform is mobile, mobile store button should be displayed if viewed on mobile device
Similar to what happens on the experiment details page. We should not now the `Get the App` Modal. Instead, we should show the appropriate mobile store icon

### LINKED ISSUE #3697: [Mobile view] The "View details" button is wrongly positioned lower than it should
**[Affected versions]:**
- Firefox 61.0 and above

**[Affected Platforms]:**
- Android 7.0 - 8.0
- iOS 11.0.1

**[Prerequisites]:**
- [Android] The "extensions.webapi.testing = true" Boolean pref was added on a new profile.

**[Steps to reproduce]:**
1. Open Firefox mobile browser and navigate to `https://testpilot.dev.mozaws.net page.
2. Observe the "View details" text button position in the "Featured Experiment" section.

**[Expected result]:**
- The button is correctly displayed between the experiment short description and TxP green install button on desktop and between experiment description and platform limitation message on mobile.

**[Actual result]:**
- The button is wrongly displayed under the TxP green install button on desktop and under the platform limitation message on mobile.

**[Additional Notes]:**
- Here is a screenshot of the issue:

view details position

### PR DESCRIPTION
**Pull request by meandavejustice**
- fixes #3670 
- fixes #3697

### CODE REVIEW

**Comment by meandavejustice** [comment]
mobile-launch-featured-on-desktop
mobile-launch-featured-on-mobile

**Comment by johngruen** [comment]
@meandavejustice R+ with a micro addition...put this in the featured experiment index.scss file at line 261 above the featured-experiment__video block

```
  .featured-experiment__actions {
    .button.mobile {
      @include respond-to('small') {
        margin: 20px auto 0;
      }

      border: 0;
      margin: 0;

      img {
        height: 60px;
        width: auto;
      }
    }
  }
``` 

and on lines 27 and 31 flip the 5 and 6

**Comment by meandavejustice** [comment]
after tweaks
gruen-update

**Comment by johngruen** [comment]
Merge when green R+

**Pull request merged**
