### PR TITLE
update tab center URL

### PR DESCRIPTION
**Pull request by clouserw**

### CODE REVIEW

**Comment by pdehaan** [comment]
I think the only other non-conforming `xpi_url` in /api/experiments.json was the Universal Search one, but possibly not relevant due to retirement:

```sh
$ http https://testpilot.firefox.com/api/experiments.json | grep "xpi_url"

      "xpi_url": "https://testpilot.firefox.com/files/activitystream/latest",
      "xpi_url": "https://testpilot.firefox.com/files/min-vid/latest",
      "xpi_url": "https://testpilot.firefox.com/files/nomore404s/latest",
      "xpi_url": "https://testpilot.firefox.com/files/pageshot/latest",
      "xpi_url": "https://people.mozilla.org/~bwinton/TabCenter/tab-center.xpi",
      "xpi_url": "https://testpilot.firefox.com/files/blok/latest",
      "xpi_url": "https://s3-us-west-2.amazonaws.com/universal-search/universal-search.xpi",
```

**Comment by clouserw** [comment]
thanks @pdehaan -- yeah, shouldn't be a problem now.  We could probably strip all of that out if we wanted to bother.

**Comment by pdehaan** [comment]
> But yeah, tested the new URL and it downloaded tab_center.xpi for me, so R+. :+1:

Not to be too pedantic, but it downloaded tab-center.xpi, right?  the one with the underscore was the old one

**Comment by lmorchard** [comment]
Yup, downloaded tab-center.xpi for me. LGTM. 
screenshot 2016-12-02 16 26 10

**Comment by ghost** [comment]
Errr... I think I edited @pdehaan's comment instead of replying to it and quoting it.  Sorry! Interneting is hard.  Thanks for landing.

**Pull request merged**
