### PR TITLE
Fix #3536.  Add SSL to font connection CSP

### LINKED ISSUE #3536: Dev website uses wrong font across all its pages
**[Affected versions]:**
- Firefox 59.0.3 and above

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Prerequisites]:**
- Following 4 prefs have been set or added on a new profile: `xpinstall.signatures.required` = `false`, testpilot.env` = `dev`, `extensions.webapi.testing` = `true` and `extensions.install.requireBuiltInCerts` = `false`

**[Steps to reproduce]:**
1. Open Firefox browser and navigate to "https://testpilot.dev.mozaws.net" page.
2. Observe the font used all across the website.
3. Open a new tab and navigate to "https://testpilot.firefox.com page.
4. Compare the font used on both pages by switching between tabs. 

**[Expected result]:**
- Both the Dev and Production websites use the same font.

**[Actual result]:**
- The Dev website uses a different font than it should. 

**[Notes]**
- This issue reproduces on all the website pages and even if TxP add-on is installed or not.
- The Stage server is not affected which means the issue appeared after recent changes.
- Here is a screenshot of the issue:

wrong font dev

### PR DESCRIPTION
**Pull request by clouserw**
This adds SSL.  I don't know if that's the fix or not, but it's the only thing that is different.

I dropped the comment about server.js because I can't find that file anymore.  If it exists somewhere, it sounds like it's important to update too.

### CODE REVIEW

**Comment by lmorchard** [comment]
> I dropped the comment about server.js because I can't find that file anymore. If it exists somewhere, it sounds like it's important to update too.

Ah, yeah, that still exists and still important to update for local dev - it's over here now:

https://github.com/mozilla/testpilot/blob/master/frontend/lib/dev-server.js#L9

**Comment by meandavejustice** [comment]
happy to merge after `frontent/lib/dev-server.js` is updated

**Comment by clouserw** [comment]
@lmorchard thanks for finding that file.  New patch squashed in

**Comment by lmorchard** [comment]
Went ahead and merged - hopefully this fixes it up on the next auto-deploy to dev!

**Comment by ghost** [comment]
This looks fixed on https://testpilot.dev.mozaws.net/ to me

**Pull request merged**
