### PR TITLE
Revert "fix error message to help with resist fingerprinting"

### PR DESCRIPTION
**Pull request by meandavejustice**
Reverts mozilla/testpilot#3486

### CODE REVIEW

**Comment by MozillaTestPilotStorybook** [comment]
# Storybook Deployment
Pull Request: http://testpilot-storybook.dev.mozaws.net/pull/3487/index.html
Commit: http://testpilot-storybook.dev.mozaws.net/f11d6dd53c904e3a9c7595b56f0c672e102b3a12/

**Comment by flodolo** [comment]
What happened?

**Comment by fzzzy** [comment]
@flodolo the strings were not localized yet, so it needs to wait until next sprint.

**Comment by flodolo** [comment]
OK, thanks for the explanation.

**Pull request closed without merging**
