### PR TITLE
Add static-dev and static-stage envs for add-on

### LINKED ISSUE #1319: Add new static dev environments to add-on
I propose two new hosts for our static deployment track:
- https://testpilot-static.dev.mozaws.net
- https://testpilot-static.stage.mozaws.net

The add-on should support both of these in the `testpilot.env` preference

### PR DESCRIPTION
**Pull request by lmorchard**
Fixes #1319

### CODE REVIEW

**Comment by lmorchard** [comment]
I'm not very creative, so I just turned the dev & stage critters upside down for the static counterparts in groundcontrol

**Comment by dannycoates** [comment]
👍

Side note: I'm trying out an 'any' [option](https://github.com/dannycoates/x16/commit/e3e9a97df05cf1113294b7d3b89d4023a8f57117) in x16. It makes the addon work with any page that uses the `message-bridge`. It isn't meant to replace the presets, but allows you to try the addon with "unofficial" txp deployments, like say for a deployment per PR branch.

**Comment by lmorchard** [comment]
Think I'll merge this. We should circle back and think about adding an 'any' option, because that would more easily let us deploy many environments - e.g. for UX testing for issue #525

**Comment by lmorchard** [comment]
Filed #1325 as a followup

**Pull request merged**
