### PR TITLE
add layout component

### PR DESCRIPTION
**Pull request by johngruen**
This PR moves the layout wrapper into its own component and adds stories

### CODE REVIEW

**Comment by meandavejustice** [comment]
@johngruen just a linting error, happy to merge once that's fixed

**Comment by johngruen** [comment]
will do today

**Comment by johngruen** [comment]
@meandavejustice should be fixed

**Comment by MozillaTestPilotStorybook** [comment]
# Storybook Deployment
Pull Request: http://testpilot-storybook.dev.mozaws.net/pull/3090/index.html
Commit: http://testpilot-storybook.dev.mozaws.net/a155f93c0bc3a60f0d9982488a4743d166540b99/

**Pull request merged**
