### PR TITLE
preload tour images

### LINKED ISSUE #1477: We should do some preloading for tour images
Right now the images only get loaded when the modal gets rendered in the page view. Might be nice to preload in the background them when we load the page so users don't get the load jank on the modal

### PR DESCRIPTION
**Pull request by dannycoates**
fixes #1477 

It's hard to perceive a difference on localhost, but I *think* it's working as intended. I see it working when I simulate a slow connection.

### CODE REVIEW

**Comment by MozillaTestPilotStorybook** [comment]
# Storybook Deployment
Pull Request: http://testpilot-storybook.dev.mozaws.net/pull/3460/index.html
Commit: http://testpilot-storybook.dev.mozaws.net/ced780227923944d88f88ca26f0cf26474ffbbae/

**Comment by MozillaTestPilotStorybook** [comment]
# Storybook Deployment
Pull Request: http://testpilot-storybook.dev.mozaws.net/pull/3460/index.html
Commit: http://testpilot-storybook.dev.mozaws.net/2733d4f4ab0b0dbcccd9b72e8fe8ffbda284b443/

**Comment by MozillaTestPilotStorybook** [comment]
# Storybook Deployment
Pull Request: http://testpilot-storybook.dev.mozaws.net/pull/3460/index.html
Commit: http://testpilot-storybook.dev.mozaws.net/ed8b84c1bc113685b769601d9765e0fb7d81edab/

**Comment by lmorchard** [comment]
Seems to work for me!

**Pull request merged**
