### PR TITLE
Finalize assets for new experiments

### PR DESCRIPTION
**Pull request by johngruen**

### CODE REVIEW

**Comment by johngruen** [comment]
Uh oh

**Comment by MozillaTestPilotStorybook** [comment]
# Storybook Deployment
Pull Request: http://testpilot-storybook.dev.mozaws.net/pull/3584/index.html
Commit: http://testpilot-storybook.dev.mozaws.net/d25e1cf9663877c7a562acb0cabb3a8840aa0f92/

**Comment by MozillaTestPilotStorybook** [comment]
# Storybook Deployment
Pull Request: http://testpilot-storybook.dev.mozaws.net/pull/3584/index.html
Commit: http://testpilot-storybook.dev.mozaws.net/f1f21ecb7846f8253ff3c9f5396b4bbe319bb785/

**Comment by flodolo** [comment]
A reminder that strings are not localized until merged into the l10n branch.

**Comment by ghost** [comment]
Thanks flod.  I merged master -> l10n

**Pull request merged**
