### PR TITLE
Added mobile download buttons

### LINKED ISSUE #3504: Experiment Control UI
It looks like we will have four experiment platforms soon, and we'll need to make sure that all combinations are accounted for when displaying Experiment Controls on different platforms. For example, if Send has a mobile app, there will need to be buttons to go to the site, get the app, and for a privacy link. If Notes as a mobile app, there will need to be buttons to go to install the add-on, get the app, and get the privacy link. If i'm viewing either of these experiments on a mobile device, i just need to see thew app store icon and privacy link.

So here's the precedence for experiment control buttons:

## Desktop
1. One Click Install (install test pilot and add-on) (`primary`)
1. Legal string (if showing one click install)
1. Enable Experiment (add-on control if test pilot is installed) (`default` button colors if )
1. Visit Experiment (web-control) (`default` if no add-on, otherwise `secondary`)
1. Get Mobile App (mobile modal trigger) (`secondary`, unless no add-on or website, then `default`)
1. Your Privacy

## Mobile (if applicable)
1. App store badge (link to app store)
1. Visit Experiment Website (optional, this should be a boolean field in YAML like `list_site_for_mobile`)
1. Your Privacy

### LINKED ISSUE #3506: Experiment DetailsMobile and Responsive UI Updates
Responsive Desktop View:
https://mozilla.github.io/testpilot-assets/Test_Pilot_Website/01_Measurements/Mobile_experiment_integration/#artboard4

iOS & Android:
https://mozilla.github.io/testpilot-assets/Test_Pilot_Website/01_Measurements/Mobile_experiment_integration/#artboard9
https://mozilla.github.io/testpilot-assets/Test_Pilot_Website/01_Measurements/Mobile_experiment_integration/#artboard1

### PR DESCRIPTION
**Pull request by dannycoates**
closes #3504 
closes #3506

Some examples:
screen shot 2018-05-07 at 3 29 58 pm
screen shot 2018-05-07 at 3 44 12 pm

### CODE REVIEW

**Comment by MozillaTestPilotStorybook** [comment]
# Storybook Deployment
Pull Request: http://testpilot-storybook.dev.mozaws.net/pull/3535/index.html
Commit: http://testpilot-storybook.dev.mozaws.net/d7d39b13503c69b7c8d68b45ad619b69e3b010ea/

**Comment by MozillaTestPilotStorybook** [comment]
# Storybook Deployment
Pull Request: http://testpilot-storybook.dev.mozaws.net/pull/3535/index.html
Commit: http://testpilot-storybook.dev.mozaws.net/0d45457f0b80f76a7097dc084e4220f71cbe1341/

**Comment by meandavejustice** [comment]
Seems weird that google play button is below the install button while the App Store button is below the "go to send" button

**Comment by MozillaTestPilotStorybook** [comment]
# Storybook Deployment
Pull Request: http://testpilot-storybook.dev.mozaws.net/pull/3535/index.html
Commit: http://testpilot-storybook.dev.mozaws.net/946d714e2b1735c2e63e52ab62a234616a649b9a/

**Comment by dannycoates** [comment]
> Seems weird that google play button is below the install button while the App Store button is below the "go to send" button

It's according to the order in #3504.  It's defined by the order of the `platforms` in the yaml file so that it's manually adjustable.

**Comment by dannycoates** [comment]
I think the mobile buttons might need some more styling love but the mechanics are ready.

**Comment by SoftVision-PaulOiegas** [comment]
@dannycoates Since Storybook = deceased for some time now (404), what do I need to modify to see the buttons/functionality on local? 
Also, would be nice to have this in test for at least a few days on dev before releasing it to production. Can we "hack" something so we can test it? Maybe have it on dev with a link to Firefox release app from market, until we have the Notes Mobile added to dev server?

**Comment by dannycoates** [comment]
To see the buttons locally add 'ios' and 'android' to the `platform` section of an experiment yaml file https://github.com/mozilla/testpilot/blob/master/docs/content/reference.md#platform. 

> Can we "hack" something so we can test it?

I added ios to the dev example experiment.

**Comment by SoftVision-PaulOiegas** [comment]
Great, thanks Danny! 👍

**Pull request merged**
